/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AssessmentPackage,
  AssessmentPackage$inboundSchema,
} from "./assessmentpackage.js";
import { RawResponse, RawResponse$inboundSchema } from "./rawresponse.js";

export type AssessmentPackagePaginated = {
  data: Array<AssessmentPackage>;
  next?: string | null | undefined;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  nextPage?: string | null | undefined;
  raw?: Array<RawResponse> | null | undefined;
};

/** @internal */
export const AssessmentPackagePaginated$inboundSchema: z.ZodType<
  AssessmentPackagePaginated,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(AssessmentPackage$inboundSchema),
  next: z.nullable(z.string()).optional(),
  next_page: z.nullable(z.string()).optional(),
  raw: z.nullable(z.array(RawResponse$inboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    "next_page": "nextPage",
  });
});

export function assessmentPackagePaginatedFromJSON(
  jsonString: string,
): SafeParseResult<AssessmentPackagePaginated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssessmentPackagePaginated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssessmentPackagePaginated' from JSON`,
  );
}
