/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Assignment, Assignment$inboundSchema } from "./assignment.js";
import { RawResponse, RawResponse$inboundSchema } from "./rawresponse.js";

export type AssignmentsPaginated = {
  data: Array<Assignment>;
  next?: string | null | undefined;
  raw?: Array<RawResponse> | null | undefined;
};

/** @internal */
export const AssignmentsPaginated$inboundSchema: z.ZodType<
  AssignmentsPaginated,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(Assignment$inboundSchema),
  next: z.nullable(z.string()).optional(),
  raw: z.nullable(z.array(RawResponse$inboundSchema)).optional(),
});

export function assignmentsPaginatedFromJSON(
  jsonString: string,
): SafeParseResult<AssignmentsPaginated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssignmentsPaginated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssignmentsPaginated' from JSON`,
  );
}
