/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  CreatePackage,
  CreatePackage$Outbound,
  CreatePackage$outboundSchema,
} from "./createpackage.js";

export type AtsCreateBackgroundCheckPackagesRequestDto = {
  /**
   * Package description
   */
  description?: string | null | undefined;
  /**
   * Package name
   */
  name?: string | null | undefined;
  /**
   * Value to pass through to the provider
   */
  passthrough?: { [k: string]: any } | null | undefined;
  /**
   * Package tests
   */
  tests?: Array<CreatePackage> | null | undefined;
};

/** @internal */
export type AtsCreateBackgroundCheckPackagesRequestDto$Outbound = {
  description?: string | null | undefined;
  name?: string | null | undefined;
  passthrough?: { [k: string]: any } | null | undefined;
  tests?: Array<CreatePackage$Outbound> | null | undefined;
};

/** @internal */
export const AtsCreateBackgroundCheckPackagesRequestDto$outboundSchema:
  z.ZodType<
    AtsCreateBackgroundCheckPackagesRequestDto$Outbound,
    z.ZodTypeDef,
    AtsCreateBackgroundCheckPackagesRequestDto
  > = z.object({
    description: z.nullable(z.string()).optional(),
    name: z.nullable(z.string()).optional(),
    passthrough: z.nullable(z.record(z.any())).optional(),
    tests: z.nullable(z.array(CreatePackage$outboundSchema)).optional(),
  });

export function atsCreateBackgroundCheckPackagesRequestDtoToJSON(
  atsCreateBackgroundCheckPackagesRequestDto:
    AtsCreateBackgroundCheckPackagesRequestDto,
): string {
  return JSON.stringify(
    AtsCreateBackgroundCheckPackagesRequestDto$outboundSchema.parse(
      atsCreateBackgroundCheckPackagesRequestDto,
    ),
  );
}
