/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { ChannelsEnum, ChannelsEnum$inboundSchema } from "./channelsenum.js";
import { Message, Message$inboundSchema } from "./createmessage.js";

export enum Campaign2 {
  True = "true",
  False = "false",
}

export type Archived = boolean | Campaign2;

export enum CampaignSchemas2 {
  True = "true",
  False = "false",
}

export type Draft = boolean | CampaignSchemas2;

export type Campaign4 = {};

/**
 * The source value of the schedule type.
 */
export type CampaignSourceValue =
  | string
  | number
  | boolean
  | Campaign4
  | Array<any>;

/**
 * The schedule type of the campaign.
 */
export enum CampaignValue {
  Immediate = "immediate",
  Scheduled = "scheduled",
  Recurring = "recurring",
  Custom = "custom",
  Triggered = "triggered",
  UnmappedValue = "unmapped_value",
}
/**
 * The schedule type of the campaign.
 */
export type CampaignValueOpen = OpenEnum<typeof CampaignValue>;

/**
 * The schedule type
 */
export type ScheduleType = {
  /**
   * The source value of the schedule type.
   */
  sourceValue?:
    | string
    | number
    | boolean
    | Campaign4
    | Array<any>
    | null
    | undefined;
  /**
   * The schedule type of the campaign.
   */
  value?: CampaignValueOpen | null | undefined;
};

export type CampaignSchemas4 = {};

/**
 * The source value of the Status.
 */
export type CampaignSchemasSourceValue =
  | string
  | number
  | boolean
  | CampaignSchemas4
  | Array<any>;

/**
 * The Status of the campaign.
 */
export enum CampaignSchemasValue {
  Draft = "draft",
  Archived = "archived",
  Live = "live",
  UnmappedValue = "unmapped_value",
}
/**
 * The Status of the campaign.
 */
export type CampaignSchemasValueOpen = OpenEnum<typeof CampaignSchemasValue>;

/**
 * Status of the Campaign
 */
export type CampaignStatus = {
  /**
   * The source value of the Status.
   */
  sourceValue?:
    | string
    | number
    | boolean
    | CampaignSchemas4
    | Array<any>
    | null
    | undefined;
  /**
   * The Status of the campaign.
   */
  value?: CampaignSchemasValueOpen | null | undefined;
};

export type Campaign = {
  archived?: boolean | Campaign2 | null | undefined;
  /**
   * channels of the Campaign
   */
  channels?: Array<ChannelsEnum> | null | undefined;
  /**
   * The created_at date
   */
  createdAt?: Date | null | undefined;
  description?: string | null | undefined;
  draft?: boolean | CampaignSchemas2 | null | undefined;
  /**
   * The first_sent_at date
   */
  firstSentAt?: Date | null | undefined;
  /**
   * Unique identifier
   */
  id?: string | null | undefined;
  /**
   * The last_sent_at date
   */
  lastSentAt?: Date | null | undefined;
  messages?: Array<Message> | null | undefined;
  name?: string | null | undefined;
  /**
   * Provider's unique identifier
   */
  remoteId?: string | null | undefined;
  /**
   * The schedule type
   */
  scheduleType?: ScheduleType | null | undefined;
  /**
   * Status of the Campaign
   */
  status?: CampaignStatus | null | undefined;
  tags?: Array<string> | null | undefined;
  /**
   * The updated_at date
   */
  updatedAt?: Date | null | undefined;
};

/** @internal */
export const Campaign2$inboundSchema: z.ZodNativeEnum<typeof Campaign2> = z
  .nativeEnum(Campaign2);

/** @internal */
export const Archived$inboundSchema: z.ZodType<
  Archived,
  z.ZodTypeDef,
  unknown
> = z.union([z.boolean(), Campaign2$inboundSchema]);

export function archivedFromJSON(
  jsonString: string,
): SafeParseResult<Archived, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Archived$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Archived' from JSON`,
  );
}

/** @internal */
export const CampaignSchemas2$inboundSchema: z.ZodNativeEnum<
  typeof CampaignSchemas2
> = z.nativeEnum(CampaignSchemas2);

/** @internal */
export const Draft$inboundSchema: z.ZodType<Draft, z.ZodTypeDef, unknown> = z
  .union([z.boolean(), CampaignSchemas2$inboundSchema]);

export function draftFromJSON(
  jsonString: string,
): SafeParseResult<Draft, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Draft$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Draft' from JSON`,
  );
}

/** @internal */
export const Campaign4$inboundSchema: z.ZodType<
  Campaign4,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function campaign4FromJSON(
  jsonString: string,
): SafeParseResult<Campaign4, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Campaign4$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Campaign4' from JSON`,
  );
}

/** @internal */
export const CampaignSourceValue$inboundSchema: z.ZodType<
  CampaignSourceValue,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.lazy(() => Campaign4$inboundSchema),
  z.array(z.any()),
]);

export function campaignSourceValueFromJSON(
  jsonString: string,
): SafeParseResult<CampaignSourceValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CampaignSourceValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CampaignSourceValue' from JSON`,
  );
}

/** @internal */
export const CampaignValue$inboundSchema: z.ZodType<
  CampaignValueOpen,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(CampaignValue);

/** @internal */
export const ScheduleType$inboundSchema: z.ZodType<
  ScheduleType,
  z.ZodTypeDef,
  unknown
> = z.object({
  source_value: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.lazy(() => Campaign4$inboundSchema),
      z.array(z.any()),
    ]),
  ).optional(),
  value: z.nullable(CampaignValue$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "source_value": "sourceValue",
  });
});

export function scheduleTypeFromJSON(
  jsonString: string,
): SafeParseResult<ScheduleType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScheduleType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScheduleType' from JSON`,
  );
}

/** @internal */
export const CampaignSchemas4$inboundSchema: z.ZodType<
  CampaignSchemas4,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function campaignSchemas4FromJSON(
  jsonString: string,
): SafeParseResult<CampaignSchemas4, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CampaignSchemas4$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CampaignSchemas4' from JSON`,
  );
}

/** @internal */
export const CampaignSchemasSourceValue$inboundSchema: z.ZodType<
  CampaignSchemasSourceValue,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.lazy(() => CampaignSchemas4$inboundSchema),
  z.array(z.any()),
]);

export function campaignSchemasSourceValueFromJSON(
  jsonString: string,
): SafeParseResult<CampaignSchemasSourceValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CampaignSchemasSourceValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CampaignSchemasSourceValue' from JSON`,
  );
}

/** @internal */
export const CampaignSchemasValue$inboundSchema: z.ZodType<
  CampaignSchemasValueOpen,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(CampaignSchemasValue);

/** @internal */
export const CampaignStatus$inboundSchema: z.ZodType<
  CampaignStatus,
  z.ZodTypeDef,
  unknown
> = z.object({
  source_value: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.lazy(() => CampaignSchemas4$inboundSchema),
      z.array(z.any()),
    ]),
  ).optional(),
  value: z.nullable(CampaignSchemasValue$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "source_value": "sourceValue",
  });
});

export function campaignStatusFromJSON(
  jsonString: string,
): SafeParseResult<CampaignStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CampaignStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CampaignStatus' from JSON`,
  );
}

/** @internal */
export const Campaign$inboundSchema: z.ZodType<
  Campaign,
  z.ZodTypeDef,
  unknown
> = z.object({
  archived: z.nullable(z.union([z.boolean(), Campaign2$inboundSchema]))
    .optional(),
  channels: z.nullable(z.array(ChannelsEnum$inboundSchema)).optional(),
  created_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  description: z.nullable(z.string()).optional(),
  draft: z.nullable(z.union([z.boolean(), CampaignSchemas2$inboundSchema]))
    .optional(),
  first_sent_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  id: z.nullable(z.string()).optional(),
  last_sent_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  messages: z.nullable(z.array(Message$inboundSchema)).optional(),
  name: z.nullable(z.string()).optional(),
  remote_id: z.nullable(z.string()).optional(),
  schedule_type: z.nullable(z.lazy(() => ScheduleType$inboundSchema))
    .optional(),
  status: z.nullable(z.lazy(() => CampaignStatus$inboundSchema)).optional(),
  tags: z.nullable(z.array(z.string())).optional(),
  updated_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "first_sent_at": "firstSentAt",
    "last_sent_at": "lastSentAt",
    "remote_id": "remoteId",
    "schedule_type": "scheduleType",
    "updated_at": "updatedAt",
  });
});

export function campaignFromJSON(
  jsonString: string,
): SafeParseResult<Campaign, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Campaign$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Campaign' from JSON`,
  );
}
