/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Campaign, Campaign$ } from "./campaign.js";
import { RawResponse, RawResponse$ } from "./rawresponse.js";
import * as z from "zod";

export type CampaignResult = {
    data: Campaign;
    raw?: Array<RawResponse> | null | undefined;
};

/** @internal */
export namespace CampaignResult$ {
    export const inboundSchema: z.ZodType<CampaignResult, z.ZodTypeDef, unknown> = z.object({
        data: Campaign$.inboundSchema,
        raw: z.nullable(z.array(RawResponse$.inboundSchema)).optional(),
    });

    export type Outbound = {
        data: Campaign$.Outbound;
        raw?: Array<RawResponse$.Outbound> | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CampaignResult> = z.object({
        data: Campaign$.outboundSchema,
        raw: z.nullable(z.array(RawResponse$.outboundSchema)).optional(),
    });
}
