/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import {
  catchUnrecognizedEnum,
  OpenEnum,
  Unrecognized,
} from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  SearchQuery,
  SearchQuery$inboundSchema,
  SearchQuery$Outbound,
  SearchQuery$outboundSchema,
} from "./searchquery.js";

/**
 * Filter parameters that allow greater customisation of the list response
 */
export type Filter = {
  /**
   * Use a string with a date to only select results updated after that given date
   */
  updatedAfter?: string | null | undefined;
};

/**
 * The additional parameters of the query
 */
export type Params = {
  /**
   * The comma separated list of fields to return in the response (if empty, all fields are returned)
   */
  fields?: string | null | undefined;
  /**
   * Filter parameters that allow greater customisation of the list response
   */
  filter?: Filter | null | undefined;
  /**
   * The unified cursor
   */
  next?: string | null | undefined;
  /**
   * The page number of the results to fetch
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  page?: string | null | undefined;
  /**
   * The number of results per page (default value is 25)
   */
  pageSize?: string | null | undefined;
  /**
   * Indicates that the raw request result should be returned in addition to the mapped result (default value is false)
   */
  raw?: boolean | null | undefined;
  /**
   * Use a string with a date to only select results updated after that given date
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  updatedAfter?: string | null | undefined;
};

/**
 * The Operator of the query
 */
export enum DocumentsFilesSearchRequestDtoOperator {
  Equal = "equal",
  NotEqual = "not_equal",
  Contain = "contain",
  LessThan = "less_than",
  GreaterThan = "greater_than",
  LessThanOrEqual = "less_than_or_equal",
  GreaterThanOrEqual = "greater_than_or_equal",
  And = "and",
  Or = "or",
  UnmappedValue = "unmapped_value",
}
/**
 * The Operator of the query
 */
export type DocumentsFilesSearchRequestDtoOperatorOpen = OpenEnum<
  typeof DocumentsFilesSearchRequestDtoOperator
>;

export type DocumentsFilesSearchRequestDto4 = {};

/**
 * The value to search for
 */
export type DocumentsFilesSearchRequestDtoValue =
  | DocumentsFilesSearchRequestDto4
  | string
  | number
  | boolean
  | Array<any>;

/**
 * The search query
 */
export type Query = {
  /**
   * The specific field to search within
   */
  field?: string | null | undefined;
  /**
   * The global search string to search in all text field
   */
  globalSearch?: string | null | undefined;
  /**
   * The Operator of the query
   */
  operator?: DocumentsFilesSearchRequestDtoOperatorOpen | null | undefined;
  /**
   * Nested queries for complex search
   */
  queries?: Array<SearchQuery> | null | undefined;
  /**
   * The value to search for
   */
  value?:
    | DocumentsFilesSearchRequestDto4
    | string
    | number
    | boolean
    | Array<any>
    | null
    | undefined;
};

export type DocumentsFilesSearchRequestDto = {
  /**
   * The additional parameters of the query
   */
  params?: Params | null | undefined;
  /**
   * Value to pass through to the provider
   */
  passthrough?: { [k: string]: any } | null | undefined;
  /**
   * The search query
   */
  query?: Query | null | undefined;
};

/** @internal */
export const Filter$inboundSchema: z.ZodType<Filter, z.ZodTypeDef, unknown> = z
  .object({
    updated_after: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "updated_after": "updatedAfter",
    });
  });

/** @internal */
export type Filter$Outbound = {
  updated_after?: string | null | undefined;
};

/** @internal */
export const Filter$outboundSchema: z.ZodType<
  Filter$Outbound,
  z.ZodTypeDef,
  Filter
> = z.object({
  updatedAfter: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    updatedAfter: "updated_after",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Filter$ {
  /** @deprecated use `Filter$inboundSchema` instead. */
  export const inboundSchema = Filter$inboundSchema;
  /** @deprecated use `Filter$outboundSchema` instead. */
  export const outboundSchema = Filter$outboundSchema;
  /** @deprecated use `Filter$Outbound` instead. */
  export type Outbound = Filter$Outbound;
}

export function filterToJSON(filter: Filter): string {
  return JSON.stringify(Filter$outboundSchema.parse(filter));
}

export function filterFromJSON(
  jsonString: string,
): SafeParseResult<Filter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Filter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Filter' from JSON`,
  );
}

/** @internal */
export const Params$inboundSchema: z.ZodType<Params, z.ZodTypeDef, unknown> = z
  .object({
    fields: z.nullable(z.string()).optional(),
    filter: z.nullable(z.lazy(() => Filter$inboundSchema)).optional(),
    next: z.nullable(z.string()).optional(),
    page: z.nullable(z.string()).optional(),
    page_size: z.nullable(z.string()).optional(),
    raw: z.nullable(z.boolean()).optional(),
    updated_after: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "page_size": "pageSize",
      "updated_after": "updatedAfter",
    });
  });

/** @internal */
export type Params$Outbound = {
  fields?: string | null | undefined;
  filter?: Filter$Outbound | null | undefined;
  next?: string | null | undefined;
  page?: string | null | undefined;
  page_size?: string | null | undefined;
  raw?: boolean | null | undefined;
  updated_after?: string | null | undefined;
};

/** @internal */
export const Params$outboundSchema: z.ZodType<
  Params$Outbound,
  z.ZodTypeDef,
  Params
> = z.object({
  fields: z.nullable(z.string()).optional(),
  filter: z.nullable(z.lazy(() => Filter$outboundSchema)).optional(),
  next: z.nullable(z.string()).optional(),
  page: z.nullable(z.string()).optional(),
  pageSize: z.nullable(z.string()).optional(),
  raw: z.nullable(z.boolean()).optional(),
  updatedAfter: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
    updatedAfter: "updated_after",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Params$ {
  /** @deprecated use `Params$inboundSchema` instead. */
  export const inboundSchema = Params$inboundSchema;
  /** @deprecated use `Params$outboundSchema` instead. */
  export const outboundSchema = Params$outboundSchema;
  /** @deprecated use `Params$Outbound` instead. */
  export type Outbound = Params$Outbound;
}

export function paramsToJSON(params: Params): string {
  return JSON.stringify(Params$outboundSchema.parse(params));
}

export function paramsFromJSON(
  jsonString: string,
): SafeParseResult<Params, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Params$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Params' from JSON`,
  );
}

/** @internal */
export const DocumentsFilesSearchRequestDtoOperator$inboundSchema: z.ZodType<
  DocumentsFilesSearchRequestDtoOperatorOpen,
  z.ZodTypeDef,
  unknown
> = z
  .union([
    z.nativeEnum(DocumentsFilesSearchRequestDtoOperator),
    z.string().transform(catchUnrecognizedEnum),
  ]);

/** @internal */
export const DocumentsFilesSearchRequestDtoOperator$outboundSchema: z.ZodType<
  DocumentsFilesSearchRequestDtoOperatorOpen,
  z.ZodTypeDef,
  DocumentsFilesSearchRequestDtoOperatorOpen
> = z.union([
  z.nativeEnum(DocumentsFilesSearchRequestDtoOperator),
  z.string().and(z.custom<Unrecognized<string>>()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DocumentsFilesSearchRequestDtoOperator$ {
  /** @deprecated use `DocumentsFilesSearchRequestDtoOperator$inboundSchema` instead. */
  export const inboundSchema =
    DocumentsFilesSearchRequestDtoOperator$inboundSchema;
  /** @deprecated use `DocumentsFilesSearchRequestDtoOperator$outboundSchema` instead. */
  export const outboundSchema =
    DocumentsFilesSearchRequestDtoOperator$outboundSchema;
}

/** @internal */
export const DocumentsFilesSearchRequestDto4$inboundSchema: z.ZodType<
  DocumentsFilesSearchRequestDto4,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type DocumentsFilesSearchRequestDto4$Outbound = {};

/** @internal */
export const DocumentsFilesSearchRequestDto4$outboundSchema: z.ZodType<
  DocumentsFilesSearchRequestDto4$Outbound,
  z.ZodTypeDef,
  DocumentsFilesSearchRequestDto4
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DocumentsFilesSearchRequestDto4$ {
  /** @deprecated use `DocumentsFilesSearchRequestDto4$inboundSchema` instead. */
  export const inboundSchema = DocumentsFilesSearchRequestDto4$inboundSchema;
  /** @deprecated use `DocumentsFilesSearchRequestDto4$outboundSchema` instead. */
  export const outboundSchema = DocumentsFilesSearchRequestDto4$outboundSchema;
  /** @deprecated use `DocumentsFilesSearchRequestDto4$Outbound` instead. */
  export type Outbound = DocumentsFilesSearchRequestDto4$Outbound;
}

export function documentsFilesSearchRequestDto4ToJSON(
  documentsFilesSearchRequestDto4: DocumentsFilesSearchRequestDto4,
): string {
  return JSON.stringify(
    DocumentsFilesSearchRequestDto4$outboundSchema.parse(
      documentsFilesSearchRequestDto4,
    ),
  );
}

export function documentsFilesSearchRequestDto4FromJSON(
  jsonString: string,
): SafeParseResult<DocumentsFilesSearchRequestDto4, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DocumentsFilesSearchRequestDto4$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentsFilesSearchRequestDto4' from JSON`,
  );
}

/** @internal */
export const DocumentsFilesSearchRequestDtoValue$inboundSchema: z.ZodType<
  DocumentsFilesSearchRequestDtoValue,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => DocumentsFilesSearchRequestDto4$inboundSchema),
  z.string(),
  z.number(),
  z.boolean(),
  z.array(z.any()),
]);

/** @internal */
export type DocumentsFilesSearchRequestDtoValue$Outbound =
  | DocumentsFilesSearchRequestDto4$Outbound
  | string
  | number
  | boolean
  | Array<any>;

/** @internal */
export const DocumentsFilesSearchRequestDtoValue$outboundSchema: z.ZodType<
  DocumentsFilesSearchRequestDtoValue$Outbound,
  z.ZodTypeDef,
  DocumentsFilesSearchRequestDtoValue
> = z.union([
  z.lazy(() => DocumentsFilesSearchRequestDto4$outboundSchema),
  z.string(),
  z.number(),
  z.boolean(),
  z.array(z.any()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DocumentsFilesSearchRequestDtoValue$ {
  /** @deprecated use `DocumentsFilesSearchRequestDtoValue$inboundSchema` instead. */
  export const inboundSchema =
    DocumentsFilesSearchRequestDtoValue$inboundSchema;
  /** @deprecated use `DocumentsFilesSearchRequestDtoValue$outboundSchema` instead. */
  export const outboundSchema =
    DocumentsFilesSearchRequestDtoValue$outboundSchema;
  /** @deprecated use `DocumentsFilesSearchRequestDtoValue$Outbound` instead. */
  export type Outbound = DocumentsFilesSearchRequestDtoValue$Outbound;
}

export function documentsFilesSearchRequestDtoValueToJSON(
  documentsFilesSearchRequestDtoValue: DocumentsFilesSearchRequestDtoValue,
): string {
  return JSON.stringify(
    DocumentsFilesSearchRequestDtoValue$outboundSchema.parse(
      documentsFilesSearchRequestDtoValue,
    ),
  );
}

export function documentsFilesSearchRequestDtoValueFromJSON(
  jsonString: string,
): SafeParseResult<DocumentsFilesSearchRequestDtoValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DocumentsFilesSearchRequestDtoValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentsFilesSearchRequestDtoValue' from JSON`,
  );
}

/** @internal */
export const Query$inboundSchema: z.ZodType<Query, z.ZodTypeDef, unknown> = z
  .object({
    field: z.nullable(z.string()).optional(),
    global_search: z.nullable(z.string()).optional(),
    operator: z.nullable(DocumentsFilesSearchRequestDtoOperator$inboundSchema)
      .optional(),
    queries: z.nullable(z.array(SearchQuery$inboundSchema)).optional(),
    value: z.nullable(
      z.union([
        z.lazy(() => DocumentsFilesSearchRequestDto4$inboundSchema),
        z.string(),
        z.number(),
        z.boolean(),
        z.array(z.any()),
      ]),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "global_search": "globalSearch",
    });
  });

/** @internal */
export type Query$Outbound = {
  field?: string | null | undefined;
  global_search?: string | null | undefined;
  operator?: string | null | undefined;
  queries?: Array<SearchQuery$Outbound> | null | undefined;
  value?:
    | DocumentsFilesSearchRequestDto4$Outbound
    | string
    | number
    | boolean
    | Array<any>
    | null
    | undefined;
};

/** @internal */
export const Query$outboundSchema: z.ZodType<
  Query$Outbound,
  z.ZodTypeDef,
  Query
> = z.object({
  field: z.nullable(z.string()).optional(),
  globalSearch: z.nullable(z.string()).optional(),
  operator: z.nullable(DocumentsFilesSearchRequestDtoOperator$outboundSchema)
    .optional(),
  queries: z.nullable(z.array(SearchQuery$outboundSchema)).optional(),
  value: z.nullable(
    z.union([
      z.lazy(() => DocumentsFilesSearchRequestDto4$outboundSchema),
      z.string(),
      z.number(),
      z.boolean(),
      z.array(z.any()),
    ]),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    globalSearch: "global_search",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Query$ {
  /** @deprecated use `Query$inboundSchema` instead. */
  export const inboundSchema = Query$inboundSchema;
  /** @deprecated use `Query$outboundSchema` instead. */
  export const outboundSchema = Query$outboundSchema;
  /** @deprecated use `Query$Outbound` instead. */
  export type Outbound = Query$Outbound;
}

export function queryToJSON(query: Query): string {
  return JSON.stringify(Query$outboundSchema.parse(query));
}

export function queryFromJSON(
  jsonString: string,
): SafeParseResult<Query, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Query$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Query' from JSON`,
  );
}

/** @internal */
export const DocumentsFilesSearchRequestDto$inboundSchema: z.ZodType<
  DocumentsFilesSearchRequestDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  params: z.nullable(z.lazy(() => Params$inboundSchema)).optional(),
  passthrough: z.nullable(z.record(z.any())).optional(),
  query: z.nullable(z.lazy(() => Query$inboundSchema)).optional(),
});

/** @internal */
export type DocumentsFilesSearchRequestDto$Outbound = {
  params?: Params$Outbound | null | undefined;
  passthrough?: { [k: string]: any } | null | undefined;
  query?: Query$Outbound | null | undefined;
};

/** @internal */
export const DocumentsFilesSearchRequestDto$outboundSchema: z.ZodType<
  DocumentsFilesSearchRequestDto$Outbound,
  z.ZodTypeDef,
  DocumentsFilesSearchRequestDto
> = z.object({
  params: z.nullable(z.lazy(() => Params$outboundSchema)).optional(),
  passthrough: z.nullable(z.record(z.any())).optional(),
  query: z.nullable(z.lazy(() => Query$outboundSchema)).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DocumentsFilesSearchRequestDto$ {
  /** @deprecated use `DocumentsFilesSearchRequestDto$inboundSchema` instead. */
  export const inboundSchema = DocumentsFilesSearchRequestDto$inboundSchema;
  /** @deprecated use `DocumentsFilesSearchRequestDto$outboundSchema` instead. */
  export const outboundSchema = DocumentsFilesSearchRequestDto$outboundSchema;
  /** @deprecated use `DocumentsFilesSearchRequestDto$Outbound` instead. */
  export type Outbound = DocumentsFilesSearchRequestDto$Outbound;
}

export function documentsFilesSearchRequestDtoToJSON(
  documentsFilesSearchRequestDto: DocumentsFilesSearchRequestDto,
): string {
  return JSON.stringify(
    DocumentsFilesSearchRequestDto$outboundSchema.parse(
      documentsFilesSearchRequestDto,
    ),
  );
}

export function documentsFilesSearchRequestDtoFromJSON(
  jsonString: string,
): SafeParseResult<DocumentsFilesSearchRequestDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DocumentsFilesSearchRequestDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentsFilesSearchRequestDto' from JSON`,
  );
}
