/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type EmployeeCustomFields4 = {};

export type EmployeeCustomFieldsSourceValue = EmployeeCustomFields4 | string | number | boolean;

export enum EmployeeCustomFieldsSchemasValue {
    Date = "date",
    Float = "float",
    Integer = "integer",
    List = "list",
    Text = "text",
    UnmappedValue = "unmapped_value",
}

/**
 * The type of the custom field.
 */
export type EmployeeCustomFieldsType = {
    sourceValue?: EmployeeCustomFields4 | string | number | boolean | null | undefined;
    value?: EmployeeCustomFieldsSchemasValue | null | undefined;
};

/**
 * The value associated with the custom field.
 */
export type EmployeeCustomFieldsValue = {};

export type EmployeeCustomFields = {
    /**
     * The description of the custom field.
     */
    description?: string | null | undefined;
    /**
     * The unique identifier for the custom field, which defaults to the name property if the ID is not accessible.
     */
    id?: string | null | undefined;
    /**
     * The name of the custom field.
     */
    name?: string | null | undefined;
    /**
     * An array of possible options for the custom field.
     */
    options?: Array<string> | null | undefined;
    /**
     * The type of the custom field.
     */
    type?: EmployeeCustomFieldsType | null | undefined;
    /**
     * The value associated with the custom field.
     */
    value?: EmployeeCustomFieldsValue | null | undefined;
    /**
     * The unique identifier for the value of the custom field.
     */
    valueId?: string | null | undefined;
};

/** @internal */
export namespace EmployeeCustomFields4$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<EmployeeCustomFields4, z.ZodTypeDef, Inbound> = z.object(
        {}
    );

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, EmployeeCustomFields4> =
        z.object({});
}

/** @internal */
export namespace EmployeeCustomFieldsSourceValue$ {
    export type Inbound = EmployeeCustomFields4$.Inbound | string | number | boolean;

    export type Outbound = EmployeeCustomFields4$.Outbound | string | number | boolean;

    export const inboundSchema: z.ZodType<EmployeeCustomFieldsSourceValue, z.ZodTypeDef, Inbound> =
        z.union([
            z.lazy(() => EmployeeCustomFields4$.inboundSchema),
            z.string(),
            z.number(),
            z.boolean(),
        ]);

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        EmployeeCustomFieldsSourceValue
    > = z.union([
        z.lazy(() => EmployeeCustomFields4$.outboundSchema),
        z.string(),
        z.number(),
        z.boolean(),
    ]);
}

/** @internal */
export const EmployeeCustomFieldsSchemasValue$ = z.nativeEnum(EmployeeCustomFieldsSchemasValue);

/** @internal */
export namespace EmployeeCustomFieldsType$ {
    export type Inbound = {
        source_value?:
            | EmployeeCustomFields4$.Inbound
            | string
            | number
            | boolean
            | null
            | undefined;
        value?: EmployeeCustomFieldsSchemasValue | null | undefined;
    };

    export const inboundSchema: z.ZodType<EmployeeCustomFieldsType, z.ZodTypeDef, Inbound> = z
        .object({
            source_value: z
                .nullable(
                    z.union([
                        z.lazy(() => EmployeeCustomFields4$.inboundSchema),
                        z.string(),
                        z.number(),
                        z.boolean(),
                    ])
                )
                .optional(),
            value: z.nullable(EmployeeCustomFieldsSchemasValue$).optional(),
        })
        .transform((v) => {
            return {
                ...(v.source_value === undefined ? null : { sourceValue: v.source_value }),
                ...(v.value === undefined ? null : { value: v.value }),
            };
        });

    export type Outbound = {
        source_value?:
            | EmployeeCustomFields4$.Outbound
            | string
            | number
            | boolean
            | null
            | undefined;
        value?: EmployeeCustomFieldsSchemasValue | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, EmployeeCustomFieldsType> = z
        .object({
            sourceValue: z
                .nullable(
                    z.union([
                        z.lazy(() => EmployeeCustomFields4$.outboundSchema),
                        z.string(),
                        z.number(),
                        z.boolean(),
                    ])
                )
                .optional(),
            value: z.nullable(EmployeeCustomFieldsSchemasValue$).optional(),
        })
        .transform((v) => {
            return {
                ...(v.sourceValue === undefined ? null : { source_value: v.sourceValue }),
                ...(v.value === undefined ? null : { value: v.value }),
            };
        });
}

/** @internal */
export namespace EmployeeCustomFieldsValue$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<EmployeeCustomFieldsValue, z.ZodTypeDef, Inbound> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, EmployeeCustomFieldsValue> =
        z.object({});
}

/** @internal */
export namespace EmployeeCustomFields$ {
    export type Inbound = {
        description?: string | null | undefined;
        id?: string | null | undefined;
        name?: string | null | undefined;
        options?: Array<string> | null | undefined;
        type?: EmployeeCustomFieldsType$.Inbound | null | undefined;
        value?: EmployeeCustomFieldsValue$.Inbound | null | undefined;
        value_id?: string | null | undefined;
    };

    export const inboundSchema: z.ZodType<EmployeeCustomFields, z.ZodTypeDef, Inbound> = z
        .object({
            description: z.nullable(z.string()).optional(),
            id: z.nullable(z.string()).optional(),
            name: z.nullable(z.string()).optional(),
            options: z.nullable(z.array(z.string())).optional(),
            type: z.nullable(z.lazy(() => EmployeeCustomFieldsType$.inboundSchema)).optional(),
            value: z.nullable(z.lazy(() => EmployeeCustomFieldsValue$.inboundSchema)).optional(),
            value_id: z.nullable(z.string()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.options === undefined ? null : { options: v.options }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.value === undefined ? null : { value: v.value }),
                ...(v.value_id === undefined ? null : { valueId: v.value_id }),
            };
        });

    export type Outbound = {
        description?: string | null | undefined;
        id?: string | null | undefined;
        name?: string | null | undefined;
        options?: Array<string> | null | undefined;
        type?: EmployeeCustomFieldsType$.Outbound | null | undefined;
        value?: EmployeeCustomFieldsValue$.Outbound | null | undefined;
        value_id?: string | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, EmployeeCustomFields> = z
        .object({
            description: z.nullable(z.string()).optional(),
            id: z.nullable(z.string()).optional(),
            name: z.nullable(z.string()).optional(),
            options: z.nullable(z.array(z.string())).optional(),
            type: z.nullable(z.lazy(() => EmployeeCustomFieldsType$.outboundSchema)).optional(),
            value: z.nullable(z.lazy(() => EmployeeCustomFieldsValue$.outboundSchema)).optional(),
            valueId: z.nullable(z.string()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.options === undefined ? null : { options: v.options }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.value === undefined ? null : { value: v.value }),
                ...(v.valueId === undefined ? null : { value_id: v.valueId }),
            };
        });
}
