/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type HiringTeam = {
    email?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    role?: string | undefined;
    userId?: string | undefined;
};

/** @internal */
export namespace HiringTeam$ {
    export type Inbound = {
        email?: string | undefined;
        first_name?: string | undefined;
        last_name?: string | undefined;
        role?: string | undefined;
        user_id?: string | undefined;
    };

    export const inboundSchema: z.ZodType<HiringTeam, z.ZodTypeDef, Inbound> = z
        .object({
            email: z.string().optional(),
            first_name: z.string().optional(),
            last_name: z.string().optional(),
            role: z.string().optional(),
            user_id: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.email === undefined ? null : { email: v.email }),
                ...(v.first_name === undefined ? null : { firstName: v.first_name }),
                ...(v.last_name === undefined ? null : { lastName: v.last_name }),
                ...(v.role === undefined ? null : { role: v.role }),
                ...(v.user_id === undefined ? null : { userId: v.user_id }),
            };
        });

    export type Outbound = {
        email?: string | undefined;
        first_name?: string | undefined;
        last_name?: string | undefined;
        role?: string | undefined;
        user_id?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, HiringTeam> = z
        .object({
            email: z.string().optional(),
            firstName: z.string().optional(),
            lastName: z.string().optional(),
            role: z.string().optional(),
            userId: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.email === undefined ? null : { email: v.email }),
                ...(v.firstName === undefined ? null : { first_name: v.firstName }),
                ...(v.lastName === undefined ? null : { last_name: v.lastName }),
                ...(v.role === undefined ? null : { role: v.role }),
                ...(v.userId === undefined ? null : { user_id: v.userId }),
            };
        });
}
