/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TimeOffStatusEnum } from "./timeoffstatusenum";
import { TimeOffTypeEnum } from "./timeofftypeenum";
import { Expose, Transform, Type } from "class-transformer";

export class HrisCreateTimeOffRequestDto extends SpeakeasyBase {
    /**
     * The approver ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "approver_id" })
    approverId?: string;

    /**
     * The employee ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "employee_id" })
    employeeId?: string;

    /**
     * The end date of the time off request
     */
    @SpeakeasyMetadata()
    @Expose({ name: "end_date" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    endDate?: Date;

    /**
     * The start date of the time off request
     */
    @SpeakeasyMetadata()
    @Expose({ name: "start_date" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    startDate?: Date;

    /**
     * The status of the time off request
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    @Type(() => TimeOffStatusEnum)
    status?: TimeOffStatusEnum;

    /**
     * The type of the time off request
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    @Type(() => TimeOffTypeEnum)
    type?: TimeOffTypeEnum;
}
