/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { catchUnrecognizedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type HRISDepartment4 = {};

export type HRISDepartmentSourceValue =
  | string
  | number
  | boolean
  | HRISDepartment4
  | Array<any>;

export enum HRISDepartmentValue {
  Department = "department",
  Company = "company",
  Division = "division",
  Group = "group",
  Project = "project",
  Team = "team",
  UnmappedValue = "unmapped_value",
}
export type HRISDepartmentValueOpen = OpenEnum<typeof HRISDepartmentValue>;

/**
 * The type of the department group
 */
export type HRISDepartmentType = {
  sourceValue?:
    | string
    | number
    | boolean
    | HRISDepartment4
    | Array<any>
    | null
    | undefined;
  value?: HRISDepartmentValueOpen | null | undefined;
};

export type HRISDepartment = {
  /**
   * The id of the company that the group belongs to
   */
  companyId?: string | null | undefined;
  /**
   * Unique identifier
   */
  id?: string | null | undefined;
  /**
   * The name of the group
   */
  name?: string | null | undefined;
  /**
   * The list of group owner ids of the given group
   */
  ownerIds?: Array<string> | null | undefined;
  /**
   * The list of parent group ids of the given group
   */
  parentIds?: Array<string> | null | undefined;
  /**
   * Provider's id of the company that the group belongs to
   */
  remoteCompanyId?: string | null | undefined;
  /**
   * Provider's unique identifier
   */
  remoteId?: string | null | undefined;
  /**
   * The list of remote group owner ids of the given group
   */
  remoteOwnerIds?: Array<string> | null | undefined;
  /**
   * Provider's list of parent group remote ids of the given group
   */
  remoteParentIds?: Array<string> | null | undefined;
  /**
   * The type of the department group
   */
  type?: HRISDepartmentType | null | undefined;
  /**
   * Custom Unified Fields configured in your StackOne project
   */
  unifiedCustomFields?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const HRISDepartment4$inboundSchema: z.ZodType<
  HRISDepartment4,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function hrisDepartment4FromJSON(
  jsonString: string,
): SafeParseResult<HRISDepartment4, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HRISDepartment4$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HRISDepartment4' from JSON`,
  );
}

/** @internal */
export const HRISDepartmentSourceValue$inboundSchema: z.ZodType<
  HRISDepartmentSourceValue,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.lazy(() => HRISDepartment4$inboundSchema),
  z.array(z.any()),
]);

export function hrisDepartmentSourceValueFromJSON(
  jsonString: string,
): SafeParseResult<HRISDepartmentSourceValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HRISDepartmentSourceValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HRISDepartmentSourceValue' from JSON`,
  );
}

/** @internal */
export const HRISDepartmentValue$inboundSchema: z.ZodType<
  HRISDepartmentValueOpen,
  z.ZodTypeDef,
  unknown
> = z
  .union([
    z.nativeEnum(HRISDepartmentValue),
    z.string().transform(catchUnrecognizedEnum),
  ]);

/** @internal */
export const HRISDepartmentType$inboundSchema: z.ZodType<
  HRISDepartmentType,
  z.ZodTypeDef,
  unknown
> = z.object({
  source_value: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.lazy(() => HRISDepartment4$inboundSchema),
      z.array(z.any()),
    ]),
  ).optional(),
  value: z.nullable(HRISDepartmentValue$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "source_value": "sourceValue",
  });
});

export function hrisDepartmentTypeFromJSON(
  jsonString: string,
): SafeParseResult<HRISDepartmentType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HRISDepartmentType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HRISDepartmentType' from JSON`,
  );
}

/** @internal */
export const HRISDepartment$inboundSchema: z.ZodType<
  HRISDepartment,
  z.ZodTypeDef,
  unknown
> = z.object({
  company_id: z.nullable(z.string()).optional(),
  id: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  owner_ids: z.nullable(z.array(z.string())).optional(),
  parent_ids: z.nullable(z.array(z.string())).optional(),
  remote_company_id: z.nullable(z.string()).optional(),
  remote_id: z.nullable(z.string()).optional(),
  remote_owner_ids: z.nullable(z.array(z.string())).optional(),
  remote_parent_ids: z.nullable(z.array(z.string())).optional(),
  type: z.nullable(z.lazy(() => HRISDepartmentType$inboundSchema)).optional(),
  unified_custom_fields: z.nullable(z.record(z.any())).optional(),
}).transform((v) => {
  return remap$(v, {
    "company_id": "companyId",
    "owner_ids": "ownerIds",
    "parent_ids": "parentIds",
    "remote_company_id": "remoteCompanyId",
    "remote_id": "remoteId",
    "remote_owner_ids": "remoteOwnerIds",
    "remote_parent_ids": "remoteParentIds",
    "unified_custom_fields": "unifiedCustomFields",
  });
});

export function hrisDepartmentFromJSON(
  jsonString: string,
): SafeParseResult<HRISDepartment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HRISDepartment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HRISDepartment' from JSON`,
  );
}
