/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { JobPosting } from "./jobposting";
import { Expose, Type } from "class-transformer";

export class JobPostingResult extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => JobPosting)
    data: JobPosting;

    @SpeakeasyMetadata()
    @Expose({ name: "raw" })
    raw?: string;
}
