/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { List } from "./list";
import { Expose, Type } from "class-transformer";

export class ListsPaginated extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: List })
    @Expose({ name: "data" })
    @Type(() => List)
    data: List[];

    @SpeakeasyMetadata()
    @Expose({ name: "next_page" })
    nextPage: string;

    @SpeakeasyMetadata()
    @Expose({ name: "raw" })
    raw?: string;
}
