/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { OpenEnum, Unrecognized } from "../../types/enums.js";

export type LmsCreateCompletionRequestDto4 = {};

/**
 * The original result status from the provider before normalization.
 */
export type LmsCreateCompletionRequestDtoSourceValue =
  | string
  | number
  | boolean
  | LmsCreateCompletionRequestDto4
  | Array<any>;

/**
 * The StackOne unified result status.
 */
export enum LmsCreateCompletionRequestDtoValue {
  Pass = "Pass",
  Fail = "Fail",
  UnmappedValue = "unmapped_value",
}
/**
 * The StackOne unified result status.
 */
export type LmsCreateCompletionRequestDtoValueOpen = OpenEnum<
  typeof LmsCreateCompletionRequestDtoValue
>;

/**
 * The result of the completion
 */
export type LmsCreateCompletionRequestDtoResult = {
  /**
   * The original result status from the provider before normalization.
   */
  sourceValue?:
    | string
    | number
    | boolean
    | LmsCreateCompletionRequestDto4
    | Array<any>
    | null
    | undefined;
  /**
   * The StackOne unified result status.
   */
  value?: LmsCreateCompletionRequestDtoValueOpen | null | undefined;
};

export type LmsCreateCompletionRequestDto = {
  /**
   * The date the content was completed
   */
  completedAt?: Date | null | undefined;
  /**
   * The external reference associated with this content
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  contentExternalReference?: string | null | undefined;
  /**
   * The content ID associated with this completion
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  contentId?: string | null | undefined;
  /**
   * The external reference of the learning object associated with this completion, this is the main identifier for creating completions.
   */
  learningObjectExternalReference: string;
  /**
   * The id of the learning object associated with this completion. This is not required unless specified in an integration.
   */
  learningObjectId?: string | null | undefined;
  /**
   * Value to pass through to the provider
   */
  passthrough?: { [k: string]: any } | null | undefined;
  /**
   * The result of the completion
   */
  result?: LmsCreateCompletionRequestDtoResult | null | undefined;
  /**
   * ISO 8601 duration format representing the time spent on completing the learning object
   */
  timeSpent?: string | null | undefined;
};

/** @internal */
export type LmsCreateCompletionRequestDto4$Outbound = {};

/** @internal */
export const LmsCreateCompletionRequestDto4$outboundSchema: z.ZodType<
  LmsCreateCompletionRequestDto4$Outbound,
  z.ZodTypeDef,
  LmsCreateCompletionRequestDto4
> = z.object({});

export function lmsCreateCompletionRequestDto4ToJSON(
  lmsCreateCompletionRequestDto4: LmsCreateCompletionRequestDto4,
): string {
  return JSON.stringify(
    LmsCreateCompletionRequestDto4$outboundSchema.parse(
      lmsCreateCompletionRequestDto4,
    ),
  );
}

/** @internal */
export type LmsCreateCompletionRequestDtoSourceValue$Outbound =
  | string
  | number
  | boolean
  | LmsCreateCompletionRequestDto4$Outbound
  | Array<any>;

/** @internal */
export const LmsCreateCompletionRequestDtoSourceValue$outboundSchema: z.ZodType<
  LmsCreateCompletionRequestDtoSourceValue$Outbound,
  z.ZodTypeDef,
  LmsCreateCompletionRequestDtoSourceValue
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.lazy(() => LmsCreateCompletionRequestDto4$outboundSchema),
  z.array(z.any()),
]);

export function lmsCreateCompletionRequestDtoSourceValueToJSON(
  lmsCreateCompletionRequestDtoSourceValue:
    LmsCreateCompletionRequestDtoSourceValue,
): string {
  return JSON.stringify(
    LmsCreateCompletionRequestDtoSourceValue$outboundSchema.parse(
      lmsCreateCompletionRequestDtoSourceValue,
    ),
  );
}

/** @internal */
export const LmsCreateCompletionRequestDtoValue$outboundSchema: z.ZodType<
  LmsCreateCompletionRequestDtoValueOpen,
  z.ZodTypeDef,
  LmsCreateCompletionRequestDtoValueOpen
> = z.union([
  z.nativeEnum(LmsCreateCompletionRequestDtoValue),
  z.string().and(z.custom<Unrecognized<string>>()),
]);

/** @internal */
export type LmsCreateCompletionRequestDtoResult$Outbound = {
  source_value?:
    | string
    | number
    | boolean
    | LmsCreateCompletionRequestDto4$Outbound
    | Array<any>
    | null
    | undefined;
  value?: string | null | undefined;
};

/** @internal */
export const LmsCreateCompletionRequestDtoResult$outboundSchema: z.ZodType<
  LmsCreateCompletionRequestDtoResult$Outbound,
  z.ZodTypeDef,
  LmsCreateCompletionRequestDtoResult
> = z.object({
  sourceValue: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.lazy(() => LmsCreateCompletionRequestDto4$outboundSchema),
      z.array(z.any()),
    ]),
  ).optional(),
  value: z.nullable(LmsCreateCompletionRequestDtoValue$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    sourceValue: "source_value",
  });
});

export function lmsCreateCompletionRequestDtoResultToJSON(
  lmsCreateCompletionRequestDtoResult: LmsCreateCompletionRequestDtoResult,
): string {
  return JSON.stringify(
    LmsCreateCompletionRequestDtoResult$outboundSchema.parse(
      lmsCreateCompletionRequestDtoResult,
    ),
  );
}

/** @internal */
export type LmsCreateCompletionRequestDto$Outbound = {
  completed_at?: string | null | undefined;
  content_external_reference?: string | null | undefined;
  content_id?: string | null | undefined;
  learning_object_external_reference: string;
  learning_object_id?: string | null | undefined;
  passthrough?: { [k: string]: any } | null | undefined;
  result?: LmsCreateCompletionRequestDtoResult$Outbound | null | undefined;
  time_spent?: string | null | undefined;
};

/** @internal */
export const LmsCreateCompletionRequestDto$outboundSchema: z.ZodType<
  LmsCreateCompletionRequestDto$Outbound,
  z.ZodTypeDef,
  LmsCreateCompletionRequestDto
> = z.object({
  completedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  contentExternalReference: z.nullable(z.string()).optional(),
  contentId: z.nullable(z.string()).optional(),
  learningObjectExternalReference: z.string(),
  learningObjectId: z.nullable(z.string()).optional(),
  passthrough: z.nullable(z.record(z.any())).optional(),
  result: z.nullable(
    z.lazy(() => LmsCreateCompletionRequestDtoResult$outboundSchema),
  ).optional(),
  timeSpent: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    completedAt: "completed_at",
    contentExternalReference: "content_external_reference",
    contentId: "content_id",
    learningObjectExternalReference: "learning_object_external_reference",
    learningObjectId: "learning_object_id",
    timeSpent: "time_spent",
  });
});

export function lmsCreateCompletionRequestDtoToJSON(
  lmsCreateCompletionRequestDto: LmsCreateCompletionRequestDto,
): string {
  return JSON.stringify(
    LmsCreateCompletionRequestDto$outboundSchema.parse(
      lmsCreateCompletionRequestDto,
    ),
  );
}
