/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { EmailMessages, EmailMessages$ } from "./emailmessages";
import { z } from "zod";

export type MarketingCreateEmailTemplateRequestDto = {
    id?: string | null | undefined;
    messages?: Array<EmailMessages> | null | undefined;
    name?: string | null | undefined;
    tags?: Array<string> | null | undefined;
};

/** @internal */
export namespace MarketingCreateEmailTemplateRequestDto$ {
    export type Inbound = {
        id?: string | null | undefined;
        messages?: Array<EmailMessages$.Inbound> | null | undefined;
        name?: string | null | undefined;
        tags?: Array<string> | null | undefined;
    };

    export const inboundSchema: z.ZodType<
        MarketingCreateEmailTemplateRequestDto,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            id: z.string().nullable().optional(),
            messages: z.array(EmailMessages$.inboundSchema).nullable().optional(),
            name: z.string().nullable().optional(),
            tags: z.array(z.string()).nullable().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.messages === undefined ? null : { messages: v.messages }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.tags === undefined ? null : { tags: v.tags }),
            };
        });

    export type Outbound = {
        id?: string | null | undefined;
        messages?: Array<EmailMessages$.Outbound> | null | undefined;
        name?: string | null | undefined;
        tags?: Array<string> | null | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        MarketingCreateEmailTemplateRequestDto
    > = z
        .object({
            id: z.string().nullable().optional(),
            messages: z.array(EmailMessages$.outboundSchema).nullable().optional(),
            name: z.string().nullable().optional(),
            tags: z.array(z.string()).nullable().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.messages === undefined ? null : { messages: v.messages }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.tags === undefined ? null : { tags: v.tags }),
            };
        });
}
