/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PushMessages } from "./pushmessages";
import { Expose, Type } from "class-transformer";

export class MarketingCreatePushTemplateRequestDto extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    @SpeakeasyMetadata({ elemType: PushMessages })
    @Expose({ name: "messages" })
    @Type(() => PushMessages)
    messages?: PushMessages[];

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "tags" })
    tags?: string[];
}
