/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { RawResponse, RawResponse$ } from "./rawresponse";
import { Template, Template$ } from "./template";
import { z } from "zod";

export type TemplatesPaginated = {
    data: Array<Template>;
    nextPage: string;
    raw?: Array<RawResponse> | undefined;
};

/** @internal */
export namespace TemplatesPaginated$ {
    export type Inbound = {
        data: Array<Template$.Inbound>;
        next_page: string;
        raw?: Array<RawResponse$.Inbound> | undefined;
    };

    export const inboundSchema: z.ZodType<TemplatesPaginated, z.ZodTypeDef, Inbound> = z
        .object({
            data: z.array(Template$.inboundSchema),
            next_page: z.string(),
            raw: z.array(RawResponse$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                data: v.data,
                nextPage: v.next_page,
                ...(v.raw === undefined ? null : { raw: v.raw }),
            };
        });

    export type Outbound = {
        data: Array<Template$.Outbound>;
        next_page: string;
        raw?: Array<RawResponse$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, TemplatesPaginated> = z
        .object({
            data: z.array(Template$.outboundSchema),
            nextPage: z.string(),
            raw: z.array(RawResponse$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                data: v.data,
                next_page: v.nextPage,
                ...(v.raw === undefined ? null : { raw: v.raw }),
            };
        });
}
