/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateResult = {
  message: string;
  statusCode: number;
  timestamp: Date;
};

/** @internal */
export const UpdateResult$inboundSchema: z.ZodType<
  UpdateResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  statusCode: z.number(),
  timestamp: z.string().datetime({ offset: true }).transform(v => new Date(v)),
});

export function updateResultFromJSON(
  jsonString: string,
): SafeParseResult<UpdateResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateResult' from JSON`,
  );
}
