/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Content, Content$ } from "./content";
import * as z from "zod";

export type WorkEligibilitySchemasDocument4 = {};

export type WorkEligibilitySchemasSourceValue =
    | WorkEligibilitySchemasDocument4
    | string
    | number
    | boolean;

/**
 * The category of the file
 */
export type WorkEligibilityCategory = {
    sourceValue?: WorkEligibilitySchemasDocument4 | string | number | boolean | null | undefined;
    /**
     * The category of the file
     */
    value?: string | null | undefined;
};

export type WorkEligibilityDocument = {
    /**
     * The category of the file
     */
    category?: WorkEligibilityCategory | null | undefined;
    /**
     * The content of the file
     */
    contents?: Array<Content> | null | undefined;
    /**
     * The creation date of the file
     */
    createdAt?: Date | null | undefined;
    /**
     * Unique identifier
     */
    id?: string | null | undefined;
    /**
     * The name of the file
     */
    name?: string | null | undefined;
    /**
     * The path where the file is stored
     */
    path?: string | null | undefined;
    /**
     * Provider's unique identifier
     */
    remoteId?: string | null | undefined;
    /**
     * The update date of the file
     */
    updatedAt?: Date | null | undefined;
};

export type WorkEligibility4 = {};

export type WorkEligibilitySourceValue = WorkEligibility4 | string | number | boolean;

/**
 * The ISO3166-1 Alpha2 Code of the Country
 */
export enum WorkEligibilityValue {
    Af = "AF",
    Al = "AL",
    Dz = "DZ",
    As = "AS",
    Ad = "AD",
    Ao = "AO",
    Ai = "AI",
    Aq = "AQ",
    Ag = "AG",
    Ar = "AR",
    Am = "AM",
    Aw = "AW",
    Au = "AU",
    At = "AT",
    Az = "AZ",
    Bs = "BS",
    Bh = "BH",
    Bd = "BD",
    Bb = "BB",
    By = "BY",
    Be = "BE",
    Bz = "BZ",
    Bj = "BJ",
    Bm = "BM",
    Bt = "BT",
    Bo = "BO",
    Bq = "BQ",
    Ba = "BA",
    Bw = "BW",
    Bv = "BV",
    Br = "BR",
    Io = "IO",
    Bn = "BN",
    Bg = "BG",
    Bf = "BF",
    Bi = "BI",
    Kh = "KH",
    Cm = "CM",
    Ca = "CA",
    Cv = "CV",
    Ky = "KY",
    Cf = "CF",
    Td = "TD",
    Cl = "CL",
    Cn = "CN",
    Cx = "CX",
    Cc = "CC",
    Co = "CO",
    Km = "KM",
    Cg = "CG",
    Cd = "CD",
    Ck = "CK",
    Cr = "CR",
    Hr = "HR",
    Cu = "CU",
    Cw = "CW",
    Cy = "CY",
    Cz = "CZ",
    Ci = "CI",
    Dk = "DK",
    Dj = "DJ",
    Dm = "DM",
    Do = "DO",
    Ec = "EC",
    Eg = "EG",
    Sv = "SV",
    Gq = "GQ",
    Er = "ER",
    Ee = "EE",
    Et = "ET",
    Fk = "FK",
    Fo = "FO",
    Fj = "FJ",
    Fi = "FI",
    Fr = "FR",
    Gf = "GF",
    Pf = "PF",
    Tf = "TF",
    Ga = "GA",
    Gm = "GM",
    Ge = "GE",
    De = "DE",
    Gh = "GH",
    Gi = "GI",
    Gr = "GR",
    Gl = "GL",
    Gd = "GD",
    Gp = "GP",
    Gu = "GU",
    Gt = "GT",
    Gg = "GG",
    Gn = "GN",
    Gw = "GW",
    Gy = "GY",
    Ht = "HT",
    Hm = "HM",
    Va = "VA",
    Hn = "HN",
    Hk = "HK",
    Hu = "HU",
    Is = "IS",
    In = "IN",
    Id = "ID",
    Ir = "IR",
    Iq = "IQ",
    Ie = "IE",
    Im = "IM",
    Il = "IL",
    It = "IT",
    Jm = "JM",
    Jp = "JP",
    Je = "JE",
    Jo = "JO",
    Kz = "KZ",
    Ke = "KE",
    Ki = "KI",
    Kp = "KP",
    Kr = "KR",
    Kw = "KW",
    Kg = "KG",
    La = "LA",
    Lv = "LV",
    Lb = "LB",
    Ls = "LS",
    Lr = "LR",
    Ly = "LY",
    Li = "LI",
    Lt = "LT",
    Lu = "LU",
    Mo = "MO",
    Mk = "MK",
    Mg = "MG",
    Mw = "MW",
    My = "MY",
    Mv = "MV",
    Ml = "ML",
    Mt = "MT",
    Mh = "MH",
    Mq = "MQ",
    Mr = "MR",
    Mu = "MU",
    Yt = "YT",
    Mx = "MX",
    Fm = "FM",
    Md = "MD",
    Mc = "MC",
    Mn = "MN",
    Me = "ME",
    Ms = "MS",
    Ma = "MA",
    Mz = "MZ",
    Mm = "MM",
    Na = "NA",
    Nr = "NR",
    Np = "NP",
    Nl = "NL",
    Nc = "NC",
    Nz = "NZ",
    Ni = "NI",
    Ne = "NE",
    Ng = "NG",
    Nu = "NU",
    Nf = "NF",
    Mp = "MP",
    No = "NO",
    Om = "OM",
    Pk = "PK",
    Pw = "PW",
    Ps = "PS",
    Pa = "PA",
    Pg = "PG",
    Py = "PY",
    Pe = "PE",
    Ph = "PH",
    Pn = "PN",
    Pl = "PL",
    Pt = "PT",
    Pr = "PR",
    Qa = "QA",
    Ro = "RO",
    Ru = "RU",
    Rw = "RW",
    Re = "RE",
    Bl = "BL",
    Sh = "SH",
    Kn = "KN",
    Lc = "LC",
    Mf = "MF",
    Pm = "PM",
    Vc = "VC",
    Ws = "WS",
    Sm = "SM",
    St = "ST",
    Sa = "SA",
    Sn = "SN",
    Rs = "RS",
    Sc = "SC",
    Sl = "SL",
    Sg = "SG",
    Sx = "SX",
    Sk = "SK",
    Si = "SI",
    Sb = "SB",
    So = "SO",
    Za = "ZA",
    Gs = "GS",
    Ss = "SS",
    Es = "ES",
    Lk = "LK",
    Sd = "SD",
    Sr = "SR",
    Sj = "SJ",
    Sz = "SZ",
    Se = "SE",
    Ch = "CH",
    Sy = "SY",
    Tw = "TW",
    Tj = "TJ",
    Tz = "TZ",
    Th = "TH",
    Tl = "TL",
    Tg = "TG",
    Tk = "TK",
    To = "TO",
    Tt = "TT",
    Tn = "TN",
    Tr = "TR",
    Tm = "TM",
    Tc = "TC",
    Tv = "TV",
    Ug = "UG",
    Ua = "UA",
    Ae = "AE",
    Gb = "GB",
    Us = "US",
    Um = "UM",
    Uy = "UY",
    Uz = "UZ",
    Vu = "VU",
    Ve = "VE",
    Vn = "VN",
    Vg = "VG",
    Vi = "VI",
    Wf = "WF",
    Eh = "EH",
    Ye = "YE",
    Zm = "ZM",
    Zw = "ZW",
    UnmappedValue = "unmapped_value",
}

/**
 * The country code of the issued by authority
 */
export type WorkEligibilityIssuedBy = {
    sourceValue?: WorkEligibility4 | string | number | boolean | null | undefined;
    /**
     * The ISO3166-1 Alpha2 Code of the Country
     */
    value?: WorkEligibilityValue | null | undefined;
};

export type WorkEligibilitySchemas4 = {};

export type WorkEligibilitySourceType = WorkEligibilitySchemas4 | string | number | boolean;

export enum WorkEligibilitySchemasValue {
    Visa = "visa",
    Passport = "passport",
    DriverLicense = "driver_license",
    BirthCertificate = "birth_certificate",
    Other = "other",
}

export type WorkEligibilityType = {
    sourceType?: WorkEligibilitySchemas4 | string | number | boolean | null | undefined;
    value?: WorkEligibilitySchemasValue | null | undefined;
};

export type WorkEligibility = {
    document?: WorkEligibilityDocument | null | undefined;
    /**
     * Unique identifier
     */
    id?: string | null | undefined;
    /**
     * The country code of the issued by authority
     */
    issuedBy?: WorkEligibilityIssuedBy | null | undefined;
    number?: string | null | undefined;
    /**
     * Provider's unique identifier
     */
    remoteId?: string | null | undefined;
    subType?: string | null | undefined;
    type?: WorkEligibilityType | null | undefined;
    validFrom?: Date | null | undefined;
    validTo?: Date | null | undefined;
};

/** @internal */
export namespace WorkEligibilitySchemasDocument4$ {
    export const inboundSchema: z.ZodType<WorkEligibilitySchemasDocument4, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        WorkEligibilitySchemasDocument4
    > = z.object({});
}

/** @internal */
export namespace WorkEligibilitySchemasSourceValue$ {
    export const inboundSchema: z.ZodType<
        WorkEligibilitySchemasSourceValue,
        z.ZodTypeDef,
        unknown
    > = z.union([
        z.lazy(() => WorkEligibilitySchemasDocument4$.inboundSchema),
        z.string(),
        z.number(),
        z.boolean(),
    ]);

    export type Outbound = WorkEligibilitySchemasDocument4$.Outbound | string | number | boolean;
    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        WorkEligibilitySchemasSourceValue
    > = z.union([
        z.lazy(() => WorkEligibilitySchemasDocument4$.outboundSchema),
        z.string(),
        z.number(),
        z.boolean(),
    ]);
}

/** @internal */
export namespace WorkEligibilityCategory$ {
    export const inboundSchema: z.ZodType<WorkEligibilityCategory, z.ZodTypeDef, unknown> = z
        .object({
            source_value: z
                .nullable(
                    z.union([
                        z.lazy(() => WorkEligibilitySchemasDocument4$.inboundSchema),
                        z.string(),
                        z.number(),
                        z.boolean(),
                    ])
                )
                .optional(),
            value: z.nullable(z.string()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.source_value === undefined ? null : { sourceValue: v.source_value }),
                ...(v.value === undefined ? null : { value: v.value }),
            };
        });

    export type Outbound = {
        source_value?:
            | WorkEligibilitySchemasDocument4$.Outbound
            | string
            | number
            | boolean
            | null
            | undefined;
        value?: string | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WorkEligibilityCategory> = z
        .object({
            sourceValue: z
                .nullable(
                    z.union([
                        z.lazy(() => WorkEligibilitySchemasDocument4$.outboundSchema),
                        z.string(),
                        z.number(),
                        z.boolean(),
                    ])
                )
                .optional(),
            value: z.nullable(z.string()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.sourceValue === undefined ? null : { source_value: v.sourceValue }),
                ...(v.value === undefined ? null : { value: v.value }),
            };
        });
}

/** @internal */
export namespace WorkEligibilityDocument$ {
    export const inboundSchema: z.ZodType<WorkEligibilityDocument, z.ZodTypeDef, unknown> = z
        .object({
            category: z.nullable(z.lazy(() => WorkEligibilityCategory$.inboundSchema)).optional(),
            contents: z.nullable(z.array(Content$.inboundSchema)).optional(),
            created_at: z
                .nullable(
                    z
                        .string()
                        .datetime({ offset: true })
                        .transform((v) => new Date(v))
                )
                .optional(),
            id: z.nullable(z.string()).optional(),
            name: z.nullable(z.string()).optional(),
            path: z.nullable(z.string()).optional(),
            remote_id: z.nullable(z.string()).optional(),
            updated_at: z
                .nullable(
                    z
                        .string()
                        .datetime({ offset: true })
                        .transform((v) => new Date(v))
                )
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.category === undefined ? null : { category: v.category }),
                ...(v.contents === undefined ? null : { contents: v.contents }),
                ...(v.created_at === undefined ? null : { createdAt: v.created_at }),
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.path === undefined ? null : { path: v.path }),
                ...(v.remote_id === undefined ? null : { remoteId: v.remote_id }),
                ...(v.updated_at === undefined ? null : { updatedAt: v.updated_at }),
            };
        });

    export type Outbound = {
        category?: WorkEligibilityCategory$.Outbound | null | undefined;
        contents?: Array<Content$.Outbound> | null | undefined;
        created_at?: string | null | undefined;
        id?: string | null | undefined;
        name?: string | null | undefined;
        path?: string | null | undefined;
        remote_id?: string | null | undefined;
        updated_at?: string | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WorkEligibilityDocument> = z
        .object({
            category: z.nullable(z.lazy(() => WorkEligibilityCategory$.outboundSchema)).optional(),
            contents: z.nullable(z.array(Content$.outboundSchema)).optional(),
            createdAt: z.nullable(z.date().transform((v) => v.toISOString())).optional(),
            id: z.nullable(z.string()).optional(),
            name: z.nullable(z.string()).optional(),
            path: z.nullable(z.string()).optional(),
            remoteId: z.nullable(z.string()).optional(),
            updatedAt: z.nullable(z.date().transform((v) => v.toISOString())).optional(),
        })
        .transform((v) => {
            return {
                ...(v.category === undefined ? null : { category: v.category }),
                ...(v.contents === undefined ? null : { contents: v.contents }),
                ...(v.createdAt === undefined ? null : { created_at: v.createdAt }),
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.path === undefined ? null : { path: v.path }),
                ...(v.remoteId === undefined ? null : { remote_id: v.remoteId }),
                ...(v.updatedAt === undefined ? null : { updated_at: v.updatedAt }),
            };
        });
}

/** @internal */
export namespace WorkEligibility4$ {
    export const inboundSchema: z.ZodType<WorkEligibility4, z.ZodTypeDef, unknown> = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WorkEligibility4> = z.object({});
}

/** @internal */
export namespace WorkEligibilitySourceValue$ {
    export const inboundSchema: z.ZodType<WorkEligibilitySourceValue, z.ZodTypeDef, unknown> =
        z.union([
            z.lazy(() => WorkEligibility4$.inboundSchema),
            z.string(),
            z.number(),
            z.boolean(),
        ]);

    export type Outbound = WorkEligibility4$.Outbound | string | number | boolean;
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WorkEligibilitySourceValue> =
        z.union([
            z.lazy(() => WorkEligibility4$.outboundSchema),
            z.string(),
            z.number(),
            z.boolean(),
        ]);
}

/** @internal */
export const WorkEligibilityValue$: z.ZodNativeEnum<typeof WorkEligibilityValue> =
    z.nativeEnum(WorkEligibilityValue);

/** @internal */
export namespace WorkEligibilityIssuedBy$ {
    export const inboundSchema: z.ZodType<WorkEligibilityIssuedBy, z.ZodTypeDef, unknown> = z
        .object({
            source_value: z
                .nullable(
                    z.union([
                        z.lazy(() => WorkEligibility4$.inboundSchema),
                        z.string(),
                        z.number(),
                        z.boolean(),
                    ])
                )
                .optional(),
            value: z.nullable(WorkEligibilityValue$).optional(),
        })
        .transform((v) => {
            return {
                ...(v.source_value === undefined ? null : { sourceValue: v.source_value }),
                ...(v.value === undefined ? null : { value: v.value }),
            };
        });

    export type Outbound = {
        source_value?: WorkEligibility4$.Outbound | string | number | boolean | null | undefined;
        value?: WorkEligibilityValue | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WorkEligibilityIssuedBy> = z
        .object({
            sourceValue: z
                .nullable(
                    z.union([
                        z.lazy(() => WorkEligibility4$.outboundSchema),
                        z.string(),
                        z.number(),
                        z.boolean(),
                    ])
                )
                .optional(),
            value: z.nullable(WorkEligibilityValue$).optional(),
        })
        .transform((v) => {
            return {
                ...(v.sourceValue === undefined ? null : { source_value: v.sourceValue }),
                ...(v.value === undefined ? null : { value: v.value }),
            };
        });
}

/** @internal */
export namespace WorkEligibilitySchemas4$ {
    export const inboundSchema: z.ZodType<WorkEligibilitySchemas4, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WorkEligibilitySchemas4> =
        z.object({});
}

/** @internal */
export namespace WorkEligibilitySourceType$ {
    export const inboundSchema: z.ZodType<WorkEligibilitySourceType, z.ZodTypeDef, unknown> =
        z.union([
            z.lazy(() => WorkEligibilitySchemas4$.inboundSchema),
            z.string(),
            z.number(),
            z.boolean(),
        ]);

    export type Outbound = WorkEligibilitySchemas4$.Outbound | string | number | boolean;
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WorkEligibilitySourceType> =
        z.union([
            z.lazy(() => WorkEligibilitySchemas4$.outboundSchema),
            z.string(),
            z.number(),
            z.boolean(),
        ]);
}

/** @internal */
export const WorkEligibilitySchemasValue$: z.ZodNativeEnum<typeof WorkEligibilitySchemasValue> =
    z.nativeEnum(WorkEligibilitySchemasValue);

/** @internal */
export namespace WorkEligibilityType$ {
    export const inboundSchema: z.ZodType<WorkEligibilityType, z.ZodTypeDef, unknown> = z
        .object({
            source_type: z
                .nullable(
                    z.union([
                        z.lazy(() => WorkEligibilitySchemas4$.inboundSchema),
                        z.string(),
                        z.number(),
                        z.boolean(),
                    ])
                )
                .optional(),
            value: z.nullable(WorkEligibilitySchemasValue$).optional(),
        })
        .transform((v) => {
            return {
                ...(v.source_type === undefined ? null : { sourceType: v.source_type }),
                ...(v.value === undefined ? null : { value: v.value }),
            };
        });

    export type Outbound = {
        source_type?:
            | WorkEligibilitySchemas4$.Outbound
            | string
            | number
            | boolean
            | null
            | undefined;
        value?: WorkEligibilitySchemasValue | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WorkEligibilityType> = z
        .object({
            sourceType: z
                .nullable(
                    z.union([
                        z.lazy(() => WorkEligibilitySchemas4$.outboundSchema),
                        z.string(),
                        z.number(),
                        z.boolean(),
                    ])
                )
                .optional(),
            value: z.nullable(WorkEligibilitySchemasValue$).optional(),
        })
        .transform((v) => {
            return {
                ...(v.sourceType === undefined ? null : { source_type: v.sourceType }),
                ...(v.value === undefined ? null : { value: v.value }),
            };
        });
}

/** @internal */
export namespace WorkEligibility$ {
    export const inboundSchema: z.ZodType<WorkEligibility, z.ZodTypeDef, unknown> = z
        .object({
            document: z.nullable(z.lazy(() => WorkEligibilityDocument$.inboundSchema)).optional(),
            id: z.nullable(z.string()).optional(),
            issued_by: z.nullable(z.lazy(() => WorkEligibilityIssuedBy$.inboundSchema)).optional(),
            number: z.nullable(z.string()).optional(),
            remote_id: z.nullable(z.string()).optional(),
            sub_type: z.nullable(z.string()).optional(),
            type: z.nullable(z.lazy(() => WorkEligibilityType$.inboundSchema)).optional(),
            valid_from: z
                .nullable(
                    z
                        .string()
                        .datetime({ offset: true })
                        .transform((v) => new Date(v))
                )
                .optional(),
            valid_to: z
                .nullable(
                    z
                        .string()
                        .datetime({ offset: true })
                        .transform((v) => new Date(v))
                )
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.document === undefined ? null : { document: v.document }),
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.issued_by === undefined ? null : { issuedBy: v.issued_by }),
                ...(v.number === undefined ? null : { number: v.number }),
                ...(v.remote_id === undefined ? null : { remoteId: v.remote_id }),
                ...(v.sub_type === undefined ? null : { subType: v.sub_type }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.valid_from === undefined ? null : { validFrom: v.valid_from }),
                ...(v.valid_to === undefined ? null : { validTo: v.valid_to }),
            };
        });

    export type Outbound = {
        document?: WorkEligibilityDocument$.Outbound | null | undefined;
        id?: string | null | undefined;
        issued_by?: WorkEligibilityIssuedBy$.Outbound | null | undefined;
        number?: string | null | undefined;
        remote_id?: string | null | undefined;
        sub_type?: string | null | undefined;
        type?: WorkEligibilityType$.Outbound | null | undefined;
        valid_from?: string | null | undefined;
        valid_to?: string | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WorkEligibility> = z
        .object({
            document: z.nullable(z.lazy(() => WorkEligibilityDocument$.outboundSchema)).optional(),
            id: z.nullable(z.string()).optional(),
            issuedBy: z.nullable(z.lazy(() => WorkEligibilityIssuedBy$.outboundSchema)).optional(),
            number: z.nullable(z.string()).optional(),
            remoteId: z.nullable(z.string()).optional(),
            subType: z.nullable(z.string()).optional(),
            type: z.nullable(z.lazy(() => WorkEligibilityType$.outboundSchema)).optional(),
            validFrom: z.nullable(z.date().transform((v) => v.toISOString())).optional(),
            validTo: z.nullable(z.date().transform((v) => v.toISOString())).optional(),
        })
        .transform((v) => {
            return {
                ...(v.document === undefined ? null : { document: v.document }),
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.issuedBy === undefined ? null : { issued_by: v.issuedBy }),
                ...(v.number === undefined ? null : { number: v.number }),
                ...(v.remoteId === undefined ? null : { remote_id: v.remoteId }),
                ...(v.subType === undefined ? null : { sub_type: v.subType }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.validFrom === undefined ? null : { valid_from: v.validFrom }),
                ...(v.validTo === undefined ? null : { valid_to: v.validTo }),
            };
        });
}
