/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ProviderErrorApiModel, ProviderErrorApiModel$ } from "./providererrorapimodel";
import * as z from "zod";

export type WriteResultApiModel = {
    message?: string | null | undefined;
    providerErrors?: Array<ProviderErrorApiModel> | null | undefined;
    statusCode?: number | null | undefined;
    timestamp?: Date | null | undefined;
};

/** @internal */
export namespace WriteResultApiModel$ {
    export type Inbound = {
        message?: string | null | undefined;
        provider_errors?: Array<ProviderErrorApiModel$.Inbound> | null | undefined;
        statusCode?: number | null | undefined;
        timestamp?: string | null | undefined;
    };

    export const inboundSchema: z.ZodType<WriteResultApiModel, z.ZodTypeDef, Inbound> = z
        .object({
            message: z.nullable(z.string()).optional(),
            provider_errors: z.nullable(z.array(ProviderErrorApiModel$.inboundSchema)).optional(),
            statusCode: z.nullable(z.number()).optional(),
            timestamp: z
                .nullable(
                    z
                        .string()
                        .datetime({ offset: true })
                        .transform((v) => new Date(v))
                )
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.message === undefined ? null : { message: v.message }),
                ...(v.provider_errors === undefined ? null : { providerErrors: v.provider_errors }),
                ...(v.statusCode === undefined ? null : { statusCode: v.statusCode }),
                ...(v.timestamp === undefined ? null : { timestamp: v.timestamp }),
            };
        });

    export type Outbound = {
        message?: string | null | undefined;
        provider_errors?: Array<ProviderErrorApiModel$.Outbound> | null | undefined;
        statusCode?: number | null | undefined;
        timestamp?: string | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WriteResultApiModel> = z
        .object({
            message: z.nullable(z.string()).optional(),
            providerErrors: z.nullable(z.array(ProviderErrorApiModel$.outboundSchema)).optional(),
            statusCode: z.nullable(z.number()).optional(),
            timestamp: z.nullable(z.date().transform((v) => v.toISOString())).optional(),
        })
        .transform((v) => {
            return {
                ...(v.message === undefined ? null : { message: v.message }),
                ...(v.providerErrors === undefined ? null : { provider_errors: v.providerErrors }),
                ...(v.statusCode === undefined ? null : { statusCode: v.statusCode }),
                ...(v.timestamp === undefined ? null : { timestamp: v.timestamp }),
            };
        });
}
