/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

/**
 * Filter parameters that allow greater customisation of the list response
 */
export type AtsListBackgroundCheckPackagesQueryParamFilter = {
  /**
   * Use a string with a date to only select results updated after that given date
   */
  updatedAfter?: string | null | undefined;
};

export type AtsListBackgroundCheckPackagesRequest = {
  /**
   * The comma separated list of fields that will be returned in the response (if empty, all fields are returned)
   */
  fields?: string | null | undefined;
  /**
   * Filter parameters that allow greater customisation of the list response
   */
  filter?: AtsListBackgroundCheckPackagesQueryParamFilter | null | undefined;
  /**
   * The unified cursor
   */
  next?: string | null | undefined;
  /**
   * The page number of the results to fetch
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  page?: string | null | undefined;
  /**
   * The number of results per page
   */
  pageSize?: string | null | undefined;
  /**
   * Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key
   */
  proxy?: { [k: string]: any } | null | undefined;
  /**
   * Indicates that the raw request result is returned
   */
  raw?: boolean | null | undefined;
  /**
   * Use a string with a date to only select results updated after that given date
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  updatedAfter?: string | null | undefined;
  /**
   * The account identifier
   */
  xAccountId: string;
};

export type AtsListBackgroundCheckPackagesResponse = {
  /**
   * The list of background check packages was retrieved.
   */
  backgroundCheckPackagePaginated?:
    | shared.BackgroundCheckPackagePaginated
    | undefined;
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  headers: { [k: string]: Array<string> };
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export const AtsListBackgroundCheckPackagesQueryParamFilter$inboundSchema:
  z.ZodType<
    AtsListBackgroundCheckPackagesQueryParamFilter,
    z.ZodTypeDef,
    unknown
  > = z.object({
    updated_after: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "updated_after": "updatedAfter",
    });
  });

/** @internal */
export type AtsListBackgroundCheckPackagesQueryParamFilter$Outbound = {
  updated_after?: string | null | undefined;
};

/** @internal */
export const AtsListBackgroundCheckPackagesQueryParamFilter$outboundSchema:
  z.ZodType<
    AtsListBackgroundCheckPackagesQueryParamFilter$Outbound,
    z.ZodTypeDef,
    AtsListBackgroundCheckPackagesQueryParamFilter
  > = z.object({
    updatedAfter: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      updatedAfter: "updated_after",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AtsListBackgroundCheckPackagesQueryParamFilter$ {
  /** @deprecated use `AtsListBackgroundCheckPackagesQueryParamFilter$inboundSchema` instead. */
  export const inboundSchema =
    AtsListBackgroundCheckPackagesQueryParamFilter$inboundSchema;
  /** @deprecated use `AtsListBackgroundCheckPackagesQueryParamFilter$outboundSchema` instead. */
  export const outboundSchema =
    AtsListBackgroundCheckPackagesQueryParamFilter$outboundSchema;
  /** @deprecated use `AtsListBackgroundCheckPackagesQueryParamFilter$Outbound` instead. */
  export type Outbound =
    AtsListBackgroundCheckPackagesQueryParamFilter$Outbound;
}

export function atsListBackgroundCheckPackagesQueryParamFilterToJSON(
  atsListBackgroundCheckPackagesQueryParamFilter:
    AtsListBackgroundCheckPackagesQueryParamFilter,
): string {
  return JSON.stringify(
    AtsListBackgroundCheckPackagesQueryParamFilter$outboundSchema.parse(
      atsListBackgroundCheckPackagesQueryParamFilter,
    ),
  );
}

export function atsListBackgroundCheckPackagesQueryParamFilterFromJSON(
  jsonString: string,
): SafeParseResult<
  AtsListBackgroundCheckPackagesQueryParamFilter,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AtsListBackgroundCheckPackagesQueryParamFilter$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AtsListBackgroundCheckPackagesQueryParamFilter' from JSON`,
  );
}

/** @internal */
export const AtsListBackgroundCheckPackagesRequest$inboundSchema: z.ZodType<
  AtsListBackgroundCheckPackagesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  fields: z.nullable(z.string()).optional(),
  filter: z.nullable(
    z.lazy(() => AtsListBackgroundCheckPackagesQueryParamFilter$inboundSchema),
  ).optional(),
  next: z.nullable(z.string()).optional(),
  page: z.nullable(z.string()).optional(),
  page_size: z.nullable(z.string().default("25")),
  proxy: z.nullable(z.record(z.any())).optional(),
  raw: z.nullable(z.boolean().default(false)),
  updated_after: z.nullable(z.string()).optional(),
  "x-account-id": z.string(),
}).transform((v) => {
  return remap$(v, {
    "page_size": "pageSize",
    "updated_after": "updatedAfter",
    "x-account-id": "xAccountId",
  });
});

/** @internal */
export type AtsListBackgroundCheckPackagesRequest$Outbound = {
  fields?: string | null | undefined;
  filter?:
    | AtsListBackgroundCheckPackagesQueryParamFilter$Outbound
    | null
    | undefined;
  next?: string | null | undefined;
  page?: string | null | undefined;
  page_size: string | null;
  proxy?: { [k: string]: any } | null | undefined;
  raw: boolean | null;
  updated_after?: string | null | undefined;
  "x-account-id": string;
};

/** @internal */
export const AtsListBackgroundCheckPackagesRequest$outboundSchema: z.ZodType<
  AtsListBackgroundCheckPackagesRequest$Outbound,
  z.ZodTypeDef,
  AtsListBackgroundCheckPackagesRequest
> = z.object({
  fields: z.nullable(z.string()).optional(),
  filter: z.nullable(
    z.lazy(() => AtsListBackgroundCheckPackagesQueryParamFilter$outboundSchema),
  ).optional(),
  next: z.nullable(z.string()).optional(),
  page: z.nullable(z.string()).optional(),
  pageSize: z.nullable(z.string().default("25")),
  proxy: z.nullable(z.record(z.any())).optional(),
  raw: z.nullable(z.boolean().default(false)),
  updatedAfter: z.nullable(z.string()).optional(),
  xAccountId: z.string(),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
    updatedAfter: "updated_after",
    xAccountId: "x-account-id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AtsListBackgroundCheckPackagesRequest$ {
  /** @deprecated use `AtsListBackgroundCheckPackagesRequest$inboundSchema` instead. */
  export const inboundSchema =
    AtsListBackgroundCheckPackagesRequest$inboundSchema;
  /** @deprecated use `AtsListBackgroundCheckPackagesRequest$outboundSchema` instead. */
  export const outboundSchema =
    AtsListBackgroundCheckPackagesRequest$outboundSchema;
  /** @deprecated use `AtsListBackgroundCheckPackagesRequest$Outbound` instead. */
  export type Outbound = AtsListBackgroundCheckPackagesRequest$Outbound;
}

export function atsListBackgroundCheckPackagesRequestToJSON(
  atsListBackgroundCheckPackagesRequest: AtsListBackgroundCheckPackagesRequest,
): string {
  return JSON.stringify(
    AtsListBackgroundCheckPackagesRequest$outboundSchema.parse(
      atsListBackgroundCheckPackagesRequest,
    ),
  );
}

export function atsListBackgroundCheckPackagesRequestFromJSON(
  jsonString: string,
): SafeParseResult<AtsListBackgroundCheckPackagesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AtsListBackgroundCheckPackagesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AtsListBackgroundCheckPackagesRequest' from JSON`,
  );
}

/** @internal */
export const AtsListBackgroundCheckPackagesResponse$inboundSchema: z.ZodType<
  AtsListBackgroundCheckPackagesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BackgroundCheckPackagePaginated: shared
    .BackgroundCheckPackagePaginated$inboundSchema.optional(),
  ContentType: z.string(),
  Headers: z.record(z.array(z.string())),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "BackgroundCheckPackagePaginated": "backgroundCheckPackagePaginated",
    "ContentType": "contentType",
    "Headers": "headers",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type AtsListBackgroundCheckPackagesResponse$Outbound = {
  BackgroundCheckPackagePaginated?:
    | shared.BackgroundCheckPackagePaginated$Outbound
    | undefined;
  ContentType: string;
  Headers: { [k: string]: Array<string> };
  StatusCode: number;
  RawResponse: never;
};

/** @internal */
export const AtsListBackgroundCheckPackagesResponse$outboundSchema: z.ZodType<
  AtsListBackgroundCheckPackagesResponse$Outbound,
  z.ZodTypeDef,
  AtsListBackgroundCheckPackagesResponse
> = z.object({
  backgroundCheckPackagePaginated: shared
    .BackgroundCheckPackagePaginated$outboundSchema.optional(),
  contentType: z.string(),
  headers: z.record(z.array(z.string())),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
}).transform((v) => {
  return remap$(v, {
    backgroundCheckPackagePaginated: "BackgroundCheckPackagePaginated",
    contentType: "ContentType",
    headers: "Headers",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AtsListBackgroundCheckPackagesResponse$ {
  /** @deprecated use `AtsListBackgroundCheckPackagesResponse$inboundSchema` instead. */
  export const inboundSchema =
    AtsListBackgroundCheckPackagesResponse$inboundSchema;
  /** @deprecated use `AtsListBackgroundCheckPackagesResponse$outboundSchema` instead. */
  export const outboundSchema =
    AtsListBackgroundCheckPackagesResponse$outboundSchema;
  /** @deprecated use `AtsListBackgroundCheckPackagesResponse$Outbound` instead. */
  export type Outbound = AtsListBackgroundCheckPackagesResponse$Outbound;
}

export function atsListBackgroundCheckPackagesResponseToJSON(
  atsListBackgroundCheckPackagesResponse:
    AtsListBackgroundCheckPackagesResponse,
): string {
  return JSON.stringify(
    AtsListBackgroundCheckPackagesResponse$outboundSchema.parse(
      atsListBackgroundCheckPackagesResponse,
    ),
  );
}

export function atsListBackgroundCheckPackagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<AtsListBackgroundCheckPackagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AtsListBackgroundCheckPackagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AtsListBackgroundCheckPackagesResponse' from JSON`,
  );
}
