/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

/**
 * Filter parameters that allow greater customisation of the list response
 */
export type HrisListPositionsQueryParamFilter = {
  /**
   * Use a string with a date to only select results updated after that given date
   */
  updatedAfter?: Date | null | undefined;
};

/**
 * Filter positions by status
 */
export enum HrisListPositionsQueryParamStatus {
  Open = "open",
  Draft = "draft",
  Closed = "closed",
  Paused = "paused",
  UnmappedValue = "unmapped_value",
}

export type HrisListPositionsRequest = {
  /**
   * Set to "heartbeat" to enable keep-alive newline heartbeats during long-running requests. Response includes Preference-Applied: heartbeat header when honored. (RFC 7240)
   */
  prefer?: string | undefined;
  /**
   * The comma separated list of fields to return in the response (if empty, all fields are returned)
   */
  fields?: string | null | undefined;
  /**
   * Filter parameters that allow greater customisation of the list response
   */
  filter?: HrisListPositionsQueryParamFilter | null | undefined;
  /**
   * The unified cursor
   */
  next?: string | null | undefined;
  /**
   * The page number of the results to fetch
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  page?: string | null | undefined;
  /**
   * The number of results per page (default value is 25)
   */
  pageSize?: string | null | undefined;
  /**
   * Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key
   */
  proxy?: { [k: string]: any } | null | undefined;
  /**
   * Indicates that the raw request result should be returned in addition to the mapped result (default value is false)
   */
  raw?: boolean | null | undefined;
  /**
   * Filter positions by status
   */
  status?: HrisListPositionsQueryParamStatus | null | undefined;
  /**
   * Use a string with a date to only select results updated after that given date
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  updatedAfter?: Date | null | undefined;
  /**
   * The account identifier
   */
  xAccountId: string;
};

export type HrisListPositionsResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  headers: { [k: string]: Array<string> };
  /**
   * The list of positions was retrieved.
   */
  positionsPaginated?: shared.PositionsPaginated | undefined;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export type HrisListPositionsQueryParamFilter$Outbound = {
  updated_after?: string | null | undefined;
};

/** @internal */
export const HrisListPositionsQueryParamFilter$outboundSchema: z.ZodType<
  HrisListPositionsQueryParamFilter$Outbound,
  z.ZodTypeDef,
  HrisListPositionsQueryParamFilter
> = z.object({
  updatedAfter: z.nullable(z.date().transform(v => v.toISOString())).optional(),
}).transform((v) => {
  return remap$(v, {
    updatedAfter: "updated_after",
  });
});

export function hrisListPositionsQueryParamFilterToJSON(
  hrisListPositionsQueryParamFilter: HrisListPositionsQueryParamFilter,
): string {
  return JSON.stringify(
    HrisListPositionsQueryParamFilter$outboundSchema.parse(
      hrisListPositionsQueryParamFilter,
    ),
  );
}

/** @internal */
export const HrisListPositionsQueryParamStatus$outboundSchema: z.ZodNativeEnum<
  typeof HrisListPositionsQueryParamStatus
> = z.nativeEnum(HrisListPositionsQueryParamStatus);

/** @internal */
export type HrisListPositionsRequest$Outbound = {
  Prefer?: string | undefined;
  fields?: string | null | undefined;
  filter?: HrisListPositionsQueryParamFilter$Outbound | null | undefined;
  next?: string | null | undefined;
  page?: string | null | undefined;
  page_size?: string | null | undefined;
  proxy?: { [k: string]: any } | null | undefined;
  raw?: boolean | null | undefined;
  status?: string | null | undefined;
  updated_after?: string | null | undefined;
  "x-account-id": string;
};

/** @internal */
export const HrisListPositionsRequest$outboundSchema: z.ZodType<
  HrisListPositionsRequest$Outbound,
  z.ZodTypeDef,
  HrisListPositionsRequest
> = z.object({
  prefer: z.string().optional(),
  fields: z.nullable(z.string()).optional(),
  filter: z.nullable(
    z.lazy(() => HrisListPositionsQueryParamFilter$outboundSchema),
  ).optional(),
  next: z.nullable(z.string()).optional(),
  page: z.nullable(z.string()).optional(),
  pageSize: z.nullable(z.string()).optional(),
  proxy: z.nullable(z.record(z.any())).optional(),
  raw: z.nullable(z.boolean()).optional(),
  status: z.nullable(HrisListPositionsQueryParamStatus$outboundSchema)
    .optional(),
  updatedAfter: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  xAccountId: z.string(),
}).transform((v) => {
  return remap$(v, {
    prefer: "Prefer",
    pageSize: "page_size",
    updatedAfter: "updated_after",
    xAccountId: "x-account-id",
  });
});

export function hrisListPositionsRequestToJSON(
  hrisListPositionsRequest: HrisListPositionsRequest,
): string {
  return JSON.stringify(
    HrisListPositionsRequest$outboundSchema.parse(hrisListPositionsRequest),
  );
}

/** @internal */
export const HrisListPositionsResponse$inboundSchema: z.ZodType<
  HrisListPositionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Headers: z.record(z.array(z.string())).default({}),
  PositionsPaginated: shared.PositionsPaginated$inboundSchema.optional(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "Headers": "headers",
    "PositionsPaginated": "positionsPaginated",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function hrisListPositionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<HrisListPositionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HrisListPositionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HrisListPositionsResponse' from JSON`,
  );
}
