/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as shared from "../shared/index.js";
import * as z from "zod";

/**
 * Filter parameters that allow greater customisation of the list response
 */
export type HrisListJobsQueryParamFilter = {
    /**
     * Use a string with a date to only select results updated after that given date
     */
    updatedAfter?: string | null | undefined;
};

export type HrisListJobsRequest = {
    /**
     * The comma separated list of fields that will be returned in the response (if empty, all fields are returned)
     */
    fields?: string | null | undefined;
    /**
     * Filter parameters that allow greater customisation of the list response
     */
    filter?: HrisListJobsQueryParamFilter | null | undefined;
    /**
     * The unified cursor
     */
    next?: string | null | undefined;
    /**
     * The page number of the results to fetch
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    page?: string | null | undefined;
    /**
     * The number of results per page
     */
    pageSize?: string | null | undefined;
    /**
     * Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key
     */
    proxy?: { [k: string]: any } | null | undefined;
    /**
     * Indicates that the raw request result is returned
     */
    raw?: boolean | null | undefined;
    /**
     * Use a string with a date to only select results updated after that given date
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    updatedAfter?: string | null | undefined;
    /**
     * The account identifier
     */
    xAccountId: string;
};

export type HrisListJobsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * The list of jobs was retrieved.
     */
    jobsPaginated?: shared.JobsPaginated | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const HrisListJobsQueryParamFilter$inboundSchema: z.ZodType<
    HrisListJobsQueryParamFilter,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        updated_after: z.nullable(z.string()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            updated_after: "updatedAfter",
        });
    });

/** @internal */
export type HrisListJobsQueryParamFilter$Outbound = {
    updated_after?: string | null | undefined;
};

/** @internal */
export const HrisListJobsQueryParamFilter$outboundSchema: z.ZodType<
    HrisListJobsQueryParamFilter$Outbound,
    z.ZodTypeDef,
    HrisListJobsQueryParamFilter
> = z
    .object({
        updatedAfter: z.nullable(z.string()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            updatedAfter: "updated_after",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace HrisListJobsQueryParamFilter$ {
    /** @deprecated use `HrisListJobsQueryParamFilter$inboundSchema` instead. */
    export const inboundSchema = HrisListJobsQueryParamFilter$inboundSchema;
    /** @deprecated use `HrisListJobsQueryParamFilter$outboundSchema` instead. */
    export const outboundSchema = HrisListJobsQueryParamFilter$outboundSchema;
    /** @deprecated use `HrisListJobsQueryParamFilter$Outbound` instead. */
    export type Outbound = HrisListJobsQueryParamFilter$Outbound;
}

/** @internal */
export const HrisListJobsRequest$inboundSchema: z.ZodType<
    HrisListJobsRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        fields: z.nullable(z.string()).optional(),
        filter: z.nullable(z.lazy(() => HrisListJobsQueryParamFilter$inboundSchema)).optional(),
        next: z.nullable(z.string()).optional(),
        page: z.nullable(z.string()).optional(),
        page_size: z.nullable(z.string().default("25")),
        proxy: z.nullable(z.record(z.any())).optional(),
        raw: z.nullable(z.boolean().default(false)),
        updated_after: z.nullable(z.string()).optional(),
        "x-account-id": z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            page_size: "pageSize",
            updated_after: "updatedAfter",
            "x-account-id": "xAccountId",
        });
    });

/** @internal */
export type HrisListJobsRequest$Outbound = {
    fields?: string | null | undefined;
    filter?: HrisListJobsQueryParamFilter$Outbound | null | undefined;
    next?: string | null | undefined;
    page?: string | null | undefined;
    page_size: string | null;
    proxy?: { [k: string]: any } | null | undefined;
    raw: boolean | null;
    updated_after?: string | null | undefined;
    "x-account-id": string;
};

/** @internal */
export const HrisListJobsRequest$outboundSchema: z.ZodType<
    HrisListJobsRequest$Outbound,
    z.ZodTypeDef,
    HrisListJobsRequest
> = z
    .object({
        fields: z.nullable(z.string()).optional(),
        filter: z.nullable(z.lazy(() => HrisListJobsQueryParamFilter$outboundSchema)).optional(),
        next: z.nullable(z.string()).optional(),
        page: z.nullable(z.string()).optional(),
        pageSize: z.nullable(z.string().default("25")),
        proxy: z.nullable(z.record(z.any())).optional(),
        raw: z.nullable(z.boolean().default(false)),
        updatedAfter: z.nullable(z.string()).optional(),
        xAccountId: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            pageSize: "page_size",
            updatedAfter: "updated_after",
            xAccountId: "x-account-id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace HrisListJobsRequest$ {
    /** @deprecated use `HrisListJobsRequest$inboundSchema` instead. */
    export const inboundSchema = HrisListJobsRequest$inboundSchema;
    /** @deprecated use `HrisListJobsRequest$outboundSchema` instead. */
    export const outboundSchema = HrisListJobsRequest$outboundSchema;
    /** @deprecated use `HrisListJobsRequest$Outbound` instead. */
    export type Outbound = HrisListJobsRequest$Outbound;
}

/** @internal */
export const HrisListJobsResponse$inboundSchema: z.ZodType<
    HrisListJobsResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ContentType: z.string(),
        JobsPaginated: shared.JobsPaginated$inboundSchema.optional(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            ContentType: "contentType",
            JobsPaginated: "jobsPaginated",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type HrisListJobsResponse$Outbound = {
    ContentType: string;
    JobsPaginated?: shared.JobsPaginated$Outbound | undefined;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const HrisListJobsResponse$outboundSchema: z.ZodType<
    HrisListJobsResponse$Outbound,
    z.ZodTypeDef,
    HrisListJobsResponse
> = z
    .object({
        contentType: z.string(),
        jobsPaginated: shared.JobsPaginated$outboundSchema.optional(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            jobsPaginated: "JobsPaginated",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace HrisListJobsResponse$ {
    /** @deprecated use `HrisListJobsResponse$inboundSchema` instead. */
    export const inboundSchema = HrisListJobsResponse$inboundSchema;
    /** @deprecated use `HrisListJobsResponse$outboundSchema` instead. */
    export const outboundSchema = HrisListJobsResponse$outboundSchema;
    /** @deprecated use `HrisListJobsResponse$Outbound` instead. */
    export type Outbound = HrisListJobsResponse$Outbound;
}
