/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type MarketingUpdatePushTemplateRequest = {
    marketingCreatePushTemplateRequestDto: shared.MarketingCreatePushTemplateRequestDto;
    id: string;
    /**
     * The account identifier
     */
    xAccountId: string;
};

export type MarketingUpdatePushTemplateResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * Record updated successfully
     */
    createTemplateResult?: shared.CreateTemplateResult | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace MarketingUpdatePushTemplateRequest$ {
    export type Inbound = {
        MarketingCreatePushTemplateRequestDto: shared.MarketingCreatePushTemplateRequestDto$.Inbound;
        id: string;
        "x-account-id": string;
    };

    export const inboundSchema: z.ZodType<
        MarketingUpdatePushTemplateRequest,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            MarketingCreatePushTemplateRequestDto:
                shared.MarketingCreatePushTemplateRequestDto$.inboundSchema,
            id: z.string(),
            "x-account-id": z.string(),
        })
        .transform((v) => {
            return {
                marketingCreatePushTemplateRequestDto: v.MarketingCreatePushTemplateRequestDto,
                id: v.id,
                xAccountId: v["x-account-id"],
            };
        });

    export type Outbound = {
        MarketingCreatePushTemplateRequestDto: shared.MarketingCreatePushTemplateRequestDto$.Outbound;
        id: string;
        "x-account-id": string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        MarketingUpdatePushTemplateRequest
    > = z
        .object({
            marketingCreatePushTemplateRequestDto:
                shared.MarketingCreatePushTemplateRequestDto$.outboundSchema,
            id: z.string(),
            xAccountId: z.string(),
        })
        .transform((v) => {
            return {
                MarketingCreatePushTemplateRequestDto: v.marketingCreatePushTemplateRequestDto,
                id: v.id,
                "x-account-id": v.xAccountId,
            };
        });
}

/** @internal */
export namespace MarketingUpdatePushTemplateResponse$ {
    export type Inbound = {
        ContentType: string;
        CreateTemplateResult?: shared.CreateTemplateResult$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<
        MarketingUpdatePushTemplateResponse,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            ContentType: z.string(),
            CreateTemplateResult: shared.CreateTemplateResult$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.CreateTemplateResult === undefined
                    ? null
                    : { createTemplateResult: v.CreateTemplateResult }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        CreateTemplateResult?: shared.CreateTemplateResult$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        MarketingUpdatePushTemplateResponse
    > = z
        .object({
            contentType: z.string(),
            createTemplateResult: shared.CreateTemplateResult$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.createTemplateResult === undefined
                    ? null
                    : { CreateTemplateResult: v.createTemplateResult }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
