/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type StackoneAuthenticateConnectSessionResponse = {
  /**
   * The details of the authenticated connect session.
   */
  connectSession?: shared.ConnectSession | undefined;
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  headers: { [k: string]: Array<string> };
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export const StackoneAuthenticateConnectSessionResponse$inboundSchema:
  z.ZodType<StackoneAuthenticateConnectSessionResponse, z.ZodTypeDef, unknown> =
    z.object({
      ConnectSession: shared.ConnectSession$inboundSchema.optional(),
      ContentType: z.string(),

      Headers: z.record(z.array(z.string())).default({}),
      StatusCode: z.number().int(),
      RawResponse: z.instanceof(Response),
    }).transform((v) => {
      return remap$(v, {
        "ConnectSession": "connectSession",
        "ContentType": "contentType",
        "Headers": "headers",
        "StatusCode": "statusCode",
        "RawResponse": "rawResponse",
      });
    });

export function stackoneAuthenticateConnectSessionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  StackoneAuthenticateConnectSessionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      StackoneAuthenticateConnectSessionResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'StackoneAuthenticateConnectSessionResponse' from JSON`,
  );
}
