/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type StackoneGetAccountRequest = {
  id: string;
};

export type StackoneGetAccountResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  headers: { [k: string]: Array<string> };
  /**
   * The account with the given identifier was retrieved.
   */
  linkedAccount?: shared.LinkedAccount | undefined;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export type StackoneGetAccountRequest$Outbound = {
  id: string;
};

/** @internal */
export const StackoneGetAccountRequest$outboundSchema: z.ZodType<
  StackoneGetAccountRequest$Outbound,
  z.ZodTypeDef,
  StackoneGetAccountRequest
> = z.object({
  id: z.string(),
});

export function stackoneGetAccountRequestToJSON(
  stackoneGetAccountRequest: StackoneGetAccountRequest,
): string {
  return JSON.stringify(
    StackoneGetAccountRequest$outboundSchema.parse(stackoneGetAccountRequest),
  );
}

/** @internal */
export const StackoneGetAccountResponse$inboundSchema: z.ZodType<
  StackoneGetAccountResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Headers: z.record(z.array(z.string())).default({}),
  LinkedAccount: shared.LinkedAccount$inboundSchema.optional(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "Headers": "headers",
    "LinkedAccount": "linkedAccount",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function stackoneGetAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<StackoneGetAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StackoneGetAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StackoneGetAccountResponse' from JSON`,
  );
}
