/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type TicketingGetCollectionRequest = {
  /**
   * The comma separated list of fields that will be returned in the response (if empty, all fields are returned)
   */
  fields?: string | null | undefined;
  id: string;
  /**
   * Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key
   */
  proxy?: { [k: string]: any } | null | undefined;
  /**
   * Indicates that the raw request result should be returned in addition to the mapped result (default value is false)
   */
  raw?: boolean | null | undefined;
  /**
   * The account identifier
   */
  xAccountId: string;
};

export type TicketingGetCollectionResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  headers: { [k: string]: Array<string> };
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * The collection with the given identifier was retrieved.
   */
  ticketingCollectionResult?: shared.TicketingCollectionResult | undefined;
};

/** @internal */
export const TicketingGetCollectionRequest$inboundSchema: z.ZodType<
  TicketingGetCollectionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  fields: z.nullable(z.string()).optional(),
  id: z.string(),
  proxy: z.nullable(z.record(z.any())).optional(),
  raw: z.nullable(z.boolean()).optional(),
  "x-account-id": z.string(),
}).transform((v) => {
  return remap$(v, {
    "x-account-id": "xAccountId",
  });
});

/** @internal */
export type TicketingGetCollectionRequest$Outbound = {
  fields?: string | null | undefined;
  id: string;
  proxy?: { [k: string]: any } | null | undefined;
  raw?: boolean | null | undefined;
  "x-account-id": string;
};

/** @internal */
export const TicketingGetCollectionRequest$outboundSchema: z.ZodType<
  TicketingGetCollectionRequest$Outbound,
  z.ZodTypeDef,
  TicketingGetCollectionRequest
> = z.object({
  fields: z.nullable(z.string()).optional(),
  id: z.string(),
  proxy: z.nullable(z.record(z.any())).optional(),
  raw: z.nullable(z.boolean()).optional(),
  xAccountId: z.string(),
}).transform((v) => {
  return remap$(v, {
    xAccountId: "x-account-id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TicketingGetCollectionRequest$ {
  /** @deprecated use `TicketingGetCollectionRequest$inboundSchema` instead. */
  export const inboundSchema = TicketingGetCollectionRequest$inboundSchema;
  /** @deprecated use `TicketingGetCollectionRequest$outboundSchema` instead. */
  export const outboundSchema = TicketingGetCollectionRequest$outboundSchema;
  /** @deprecated use `TicketingGetCollectionRequest$Outbound` instead. */
  export type Outbound = TicketingGetCollectionRequest$Outbound;
}

export function ticketingGetCollectionRequestToJSON(
  ticketingGetCollectionRequest: TicketingGetCollectionRequest,
): string {
  return JSON.stringify(
    TicketingGetCollectionRequest$outboundSchema.parse(
      ticketingGetCollectionRequest,
    ),
  );
}

export function ticketingGetCollectionRequestFromJSON(
  jsonString: string,
): SafeParseResult<TicketingGetCollectionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TicketingGetCollectionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TicketingGetCollectionRequest' from JSON`,
  );
}

/** @internal */
export const TicketingGetCollectionResponse$inboundSchema: z.ZodType<
  TicketingGetCollectionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Headers: z.record(z.array(z.string())),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  TicketingCollectionResult: shared.TicketingCollectionResult$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "Headers": "headers",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "TicketingCollectionResult": "ticketingCollectionResult",
  });
});

/** @internal */
export type TicketingGetCollectionResponse$Outbound = {
  ContentType: string;
  Headers: { [k: string]: Array<string> };
  StatusCode: number;
  RawResponse: never;
  TicketingCollectionResult?:
    | shared.TicketingCollectionResult$Outbound
    | undefined;
};

/** @internal */
export const TicketingGetCollectionResponse$outboundSchema: z.ZodType<
  TicketingGetCollectionResponse$Outbound,
  z.ZodTypeDef,
  TicketingGetCollectionResponse
> = z.object({
  contentType: z.string(),
  headers: z.record(z.array(z.string())),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  ticketingCollectionResult: shared.TicketingCollectionResult$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    headers: "Headers",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
    ticketingCollectionResult: "TicketingCollectionResult",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TicketingGetCollectionResponse$ {
  /** @deprecated use `TicketingGetCollectionResponse$inboundSchema` instead. */
  export const inboundSchema = TicketingGetCollectionResponse$inboundSchema;
  /** @deprecated use `TicketingGetCollectionResponse$outboundSchema` instead. */
  export const outboundSchema = TicketingGetCollectionResponse$outboundSchema;
  /** @deprecated use `TicketingGetCollectionResponse$Outbound` instead. */
  export type Outbound = TicketingGetCollectionResponse$Outbound;
}

export function ticketingGetCollectionResponseToJSON(
  ticketingGetCollectionResponse: TicketingGetCollectionResponse,
): string {
  return JSON.stringify(
    TicketingGetCollectionResponse$outboundSchema.parse(
      ticketingGetCollectionResponse,
    ),
  );
}

export function ticketingGetCollectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<TicketingGetCollectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TicketingGetCollectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TicketingGetCollectionResponse' from JSON`,
  );
}
