/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKOptions, serverURLFromOptions } from "../lib/config";
import { HTTPClient } from "../lib/http";
import { ClientSDK } from "../lib/sdks";
import { Accounts } from "./accounts";
import { Connectors } from "./connectors";
import { ConnectSessions } from "./connectsessions";
import { Proxy } from "./proxy";

export class StackOne extends ClientSDK {
    private readonly options$: SDKOptions;

    constructor(options: SDKOptions = {}) {
        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
        });

        this.options$ = options;
        void this.options$;
    }

    private _accounts?: Accounts;
    get accounts() {
        return (this._accounts ??= new Accounts(this.options$));
    }

    private _connectSessions?: ConnectSessions;
    get connectSessions() {
        return (this._connectSessions ??= new ConnectSessions(this.options$));
    }

    private _connectors?: Connectors;
    get connectors() {
        return (this._connectors ??= new Connectors(this.options$));
    }

    private _proxy?: Proxy;
    get proxy() {
        return (this._proxy ??= new Proxy(this.options$));
    }
}
